### ISSUE TITLE
SF#378 where on dice of pdl bad results 

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#101]
From <http://sourceforge.net/p/pdl/bugs/378/>

> Running the following code on RHEL7:
> 
> ```perl
> #!/usr/bin/perl
> use PDL;
> 
> print "OS: ".`uname -a`;
> print "Perl: ".$^V."\n";
> print "PDL: ".$PDL::VERSION."\n";
> 
> my $pdl = PDL->new([ [[0, 0]], [[1, 1]], [[2, 2]] ]);
> print sprintf("\nPDL:%s\n", $pdl);
> my $pslice     = $pdl->where($pdl == 0);
> print sprintf("\nPDL Slice:\n%s\n", $pslice);
> 
> my $data      = $pdl->dice("X","X",[1, 0]);
> print sprintf("\nData:%s\n", $data);
> 
> my $dslice     = $data->where($data == 0);
> print sprintf("Should be same as PDL Slice\nData Slice:\n%s\n", $dslice);
> ```
> 
> Generates the following output:
> 
> ```
> OS: Linux riskrh7 3.10.0-123.9.3.el7.x86_64 #1 SMP Thu Oct 30 00:16:40 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
> Perl: v5.16.3
> PDL: 2.007_13
> 
> PDL:
> [
>  [
>   [0 0]
>  ]
>  [
>   [1 1]
>  ]
>  [
>   [2 2]
>  ]
> ]
> 
> PDL Slice:
> [0 0]
> 
> Data:
> [
>  [
>   [1 1]
>  ]
>  [
>   [0 0]
>  ]
> ]
> 
> Should be same as PDL Slice
> Data Slice:
> [7.897708e-28 3.1620201e-322]
> ```
> 
> Expected the "Data Slice" values to be the same as "PDL Slice".

**Comment by mohawk2** [comment]
Make this into a `*.t` file? Or a test in the file already testing slice functionality?
