### ISSUE TITLE
SF#379 Passing qsort an extra argument causes a segfault 

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#104]
From https://sourceforge.net/p/pdl/bugs/379/

> In PDL-2.00716:
> 
> ``` perl
> pdl> random(10)->average(1) for (0..100)
> #average doesn't take an argument, but at least ignores it.
> 
> pdl> random(10)->qsort(1) for (0..100)
> Segmentation fault: 11
> ```
> 
> I've also gotten:
> 
> ``` perl
> pdl> random(10)->qsort(1) for (0..100)
> perl(88949,0x7fff76629300) malloc: *** error for object 0x7f918384b918: incorrect checksum for freed object - object was probably modified after being freed.
> *** set a breakpoint in malloc_error_break to debug
> Abort trap: 6
> ```
> 
> It doesn't happen every time, which is why I put the postfix for() on there. Sometimes I change the for() range and that makes the segfault happen.
> 
> I see this present in 2.006 as well.
> 
> ``` perl
> Loaded PDL v2.006 (supports bad values)
> pdl> random(10)->qsort(1) for (0..100)
> pdl> random(10)->qsort(1) for (0..100)
> pdl> random(10)->qsort(1) for (0..100)
> pdl> random(10)->qsort(1) for (0..100)
> pdl> random(10)->qsort(1) for (0..100)
> pdl> random(10)->qsort(1) for (0..1000)
> DUMPING 0x7ffe1bfc4720     datatype: 0
>    State: (503564880) DATAFLOW_F|NOMYDIMS|DONTTOUCHDATA|HDRCPY|TRACEDEBUG
> Segmentation fault: 11
> ```
> 
> perldl -V attached for 2.00716.

**Comment by mohawk2** [comment]
Closed on SF 2016-10-08.
