### ISSUE TITLE
SF#382 plplot-5.11.0 comes with libplplot.a but missing libplplotd.a 

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#107]
From http://sourceforge.net/p/pdl/bugs/382/

> Graphics/PLplot/Makefile.PL will probably need some patching.
> 
> I do not have more details at the moment.

**Comment by mohawk2** [comment]
PDL::Graphics::PLplot is now a separate distro, and this problem has been fixed there by checking for both names.
