### ISSUE TITLE
SF#384 pdldoc.db is getting invalid paths to files on cygwin 

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#114]
From http://sourceforge.net/p/pdl/bugs/384/

> When I run 'pdldoc slice' for the PDL-2.008 install I get the following
> error:
> 
> ```
> pdldoc slice
> can't find file '/home/chm/local/lib/perl5/cygwin-thread-multi/PDL/../../../../../../../cygdrive/e/chm/local/lib/perl5/cygwin-thread-multi/PDL/Slices.pm' at /home/chm/local/lib/perl5/cygwin-thread-multi/PDL/Doc.pm line 780.
> PDL::Doc::funcdocs_fromfile("slice", "/home/chm/local/lib/perl5/cygwin-thread-multi/PDL/../../../.."..., IO::File=GLOB(0x6006d2e00)) called at /home/chm/local/lib/perl5/cygwin-thread-multi/PDL/Doc.pm line 771
> PDL::Doc::funcdocs(PDL::Doc=HASH(0x600597f20), "slice", IO::File=GLOB(0x6006d2e00)) called at /home/chm/local/lib/perl5/cygwin-thread-multi/PDL/Doc/Perldl.pm line 289
> PDL::Doc::Perldl::finddoc("slice") called at /home/chm/local/lib/perl5/cygwin-thread-multi/PDL/Doc/Perldl.pm line 631
> PDL::Doc::Perldl::help("slice") called at /home/chm/local/bin/pdldoc line 49
> Module PDL::Slices
> ```
> 
> The problem is that /cygdrive/e is basically e:/ so you can not go up from there ( ../ ).
> The correct path would be '/home/chm/local/lib/perl5/cygwin-thread-multi/PDL/Slices.pm' ithout the ../../.. stuff
> 
> PERL5LIB is /home/chm/local/lib/perl5 so that seems to be ok.
> 
> Any ideas for how the relative path stuff got scrambled into the correct
> path? This makes PDL-2.008 pdldoc useless (and help and apropos in the shells)
> on cygwin. We'll need to fix the problem before PDL-2.009.
> 
> Thanks,
> Chris
> 
> Apparently, if I set PERL5LIB to a path with the same root as the
> install drive, then the docs database is built consistently and then
> works with the cross-filesystem version of PERL5LIB or the
> same-filesystem one. E.g.,
> 
> ```
> PERL5LIB=/cygdrive/e/chm/local/lib/perl5
> make docs database
> pdldoc slice works
> 
> PERL5LIB=/home/chm/local/lib/perl5
> pdldoc slice works now too!
> ```
> 
> It appears the problem is in the abs2rel conversion. Unfortunately, I
> don't have more PDL devel time today.
> 
> Cheers,
> Chris

**Comment by mohawk2** [comment]
Chris noted also:

> I've verified that the work around is to set INSTALL_BASE with a path rooted in /cygdrive.
> That appears to avoid the bad path in the pdldoc.db database.

Therefore I will close this.
