### ISSUE TITLE
SF#387 PDL::IO::HDF5 wrong API function, H5Eset_auto1 has been called

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#117]
From http://sourceforge.net/p/pdl/bugs/387/

> With PDL-IO-HDF5-0.6501 + hrdf5-1.8.14 I have experienced the following test warnings (the test suit in the end PASS - so feel free to reject this bug report if you find it a non-issue).
> 
> ```
> "D:\strawberry32\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')"
> t/*.t
> t/attribPDL.t ..... 1/13 HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
>   #000: Z:/extlib/_2015Q2_.src/hdf5-1.8.14/src/H5E.c line 1625 in H5Eget_auto2(): wrong API function, H5Eset_auto1 has been called
>     major: Error API
>     minor: Can't get value
> t/attribPDL.t ..... ok
> t/file.t .......... ok
> t/group.t ......... 1/17 HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
>   #000: Z:/extlib/_2015Q2_.src/hdf5-1.8.14/src/H5E.c line 1625 in H5Eget_auto2(): wrong API function, H5Eset_auto1 has been called
>     major: Error API
>     minor: Can't get value
> t/group.t ......... ok
> t/reference.t ..... 1/2 HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
>   #000: Z:/extlib/_2015Q2_.src/hdf5-1.8.14/src/H5E.c line 1625 in H5Eget_auto2(): wrong API function, H5Eset_auto1 has been called
>     major: Error API
>     minor: Can't get value
> t/reference.t ..... ok
> t/total.t ......... 1/33 HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
>   #000: Z:/extlib/_2015Q2_.src/hdf5-1.8.14/src/H5E.c line 1625 in H5Eget_auto2(): wrong API function, H5Eset_auto1 has been called
>     major: Error API
>     minor: Can't get value
> t/total.t ......... ok
> t/unlink.t ........ 1/2 HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
>   #000: Z:/extlib/_2015Q2_.src/hdf5-1.8.14/src/H5E.c line 1625 in H5Eget_auto2(): wrong API function, H5Eset_auto1 has been called
>     major: Error API
>     minor: Can't get value
> t/unlink.t ........ ok
> t/vlenString.t .... 1/6 HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
>   #000: Z:/extlib/_2015Q2_.src/hdf5-1.8.14/src/H5E.c line 1625 in H5Eget_auto2(): wrong API function, H5Eset_auto1 has been called
>     major: Error API
>     minor: Can't get value
> t/vlenString.t .... ok
> t/xData.t ......... # xdata '[2 3 4 5 6 7 8 9 10 11 12]'
> t/xData.t ......... 1/2 # xdata '[2 3 4 5 6 7 8 9 10 11 12 13 14]'
> HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
>   #000: Z:/extlib/_2015Q2_.src/hdf5-1.8.14/src/H5E.c line 1625 in H5Eget_auto2(): wrong API function, H5Eset_auto1 has been called
>     major: Error API
>     minor: Can't get value
> t/xData.t ......... ok
> t/ztotal_index.t .. 1/7 HDF5-DIAG: Error detected in HDF5 (1.8.14) thread 0:
>   #000: Z:/extlib/_2015Q2_.src/hdf5-1.8.14/src/H5E.c line 1625 in H5Eget_auto2(): wrong API function, H5Eset_auto1 has been called
>     major: Error API
>     minor: Can't get value
> t/ztotal_index.t .. ok
> All tests successful.
> Files=9, Tests=85,  5 wallclock secs ( 0.06 usr +  0.03 sys =  0.09 CPU)
> Result: PASS
> ```

**Comment by mohawk2** [comment]
If our tests pass, there's nothing we can do. Closing until someone can explain the problem better!
