### ISSUE TITLE
use an exception class instead of strings

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#12]
https://metacpan.org/pod/failures is a good lightweight solution for that.

**Comment by mohawk2** [comment]
Can you guide me on how this would help? I have yet to run into a situation where I wanted to die with anything more than an informative error message.

**Comment by zmughal** [comment]
Sure. This helps standardise the names of things. The tests will no longer have to test against a string and users that want to capture those exceptions can know what they are catching. Moose did this for a Google Summer of Code project.

**Comment by mohawk2** [comment]
Much later: I'd want to see some example code that showed some utility for this idea, to guide how one would even create it. Otherwise, this issue isn't actionable and would need (regretfully) closing :-)

**Comment by zmughal** [comment]
In Data::Frame, it is used like this <https://github.com/EntropyOrg/p5-Data-Frame/pull/23/files>.

**Comment by mohawk2** [comment]
That's a lot of throwing. What I'm in need of is seeing corresponding catch code that would benefit from the structure this change would bring? I can see if there were `catch (...)` filter equivalents that would perform better than the regex alternative, but I have yet to see any PDL code that really would have been improved by this sort of exception-handling.

**Comment by zmughal** [comment]
Closing for now after some discussion on IRC.

I've been reading through all the `qr/throws_ok|dies_ok|croak|barf|die/` in the code and I see it is mostly going to fall under the same few exception classes if they did exist: either parameter, {I/O,format} error, programmer usage errors.

I don't know if these exceptions would be that much of a win then. I might later look at some other libraries in this space and see if they do anything interesting with exceptions and if user-facing applications make good use of them (e.g., inside of a dashboard with parameters and user supplied input data in order to display meaningful errors to the user).
