### ISSUE TITLE
SF#391 Operators called in the form "explicit call with trailing 0" give syntax error

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#125]
From http://sourceforge.net/p/pdl/bugs/391/

> The docs for many functions in `PDL::Ops` give 3 ways to call the function. Using 'lt' as an example:
> 
> ``` perl
>    $c = lt $a, $b, 0;     # explicit call with trailing 0
>    $c = $a < $b;           # overloaded call
>    $a->inplace->lt($b,0);  # modify $a inplace
> ```
> 
> The first form does not work as advertised.
> 
> ``` perl
> $a = pdl(1,2,3); $b = pdl(3,2,1);
> $c = lt $a, $b, 0;
> syntax error at (eval 67) line 4, near "= lt"
> ```
> 
> Similarly 'plus' gives this example that does not work:
> 
> ``` perl
> $c = plus $a, $b, 0;
> Usage:  PDL::plus(a,b,c,swap) (you may leave temporaries or output variables out of list)
> ```
> 
> and so on... The `->inplace` form seems to work OK.
> 
> perldl -V attached.
> 
> Marking as priority '7' because it seems pretty important, but my guess is very few people actually try to call the functions that way (as evidenced by the fact that nobody has reported this before).

**Comment by mohawk2** [comment]
This was actually fixed in 2139f08e60f8fa7a408c0f60606efb3fcbbbe15e
