### ISSUE TITLE
SF#393 Tests may fail if perl is compiled with -Duselongdouble

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#129]
From http://sourceforge.net/p/pdl/bugs/393/

> The t/limits_trans_err.t test fails on a debian/wheezy system if perl is compiled with -Duselongdouble (checked with perl 5.20.1):
> 
> ``` perl
> #   Failed test 'x symmetric trans'
> #   at t/limits_trans_err.t line 30.
> #     Structures begin differing at:
> #          $got->[0] = '-0.301029995663981198'
> #     $expected->[0] = '-0.301029995663981195'
> 
> #   Failed test 'x asymmetric trans'
> #   at t/limits_trans_err.t line 35.
> #     Structures begin differing at:
> #          $got->[0] = '-0.301029995663981198'
> #     $expected->[0] = '-0.301029995663981195'
> 
> #   Failed test 'illegal errbar lower bounds'
> #   at t/limits_trans_err.t line 42.
> #     Structures begin differing at:
> #          $got->[0] = '-0.301029995663981198'
> #     $expected->[0] = '-0.301029995663981195'
> # Looks like you failed 3 tests of 3.
> t/limits_trans_err.t ............
> ```
> 
> On a FreeBSD 10 system the test suite also fails if perl is compiled with -Duselongdouble, but a different test:
> 
> ``` perl
> #   Failed test 'q[e] returns exp(1)'
> #   at t/pdl_from_string.t line 301.
> #          got: '2.71828182845904509'
> #     expected: '2.71828182845904553'
> # Got 2.71828182845904509
> 
> #   Failed test 'q[E] returns exp(1)'
> #   at t/pdl_from_string.t line 304.
> #          got: '2.71828182845904509'
> #     expected: '2.71828182845904553'
> # Got 2.71828182845904509
> # Looks like you failed 2 tests of 113.
> t/pdl_from_string.t .............
> Dubious, test returned 2 (wstat 512, 0x200)
> Failed 2/113 subtests
>         (less 1 skipped subtest: 110 okay)
>         (3 TODO tests unexpectedly succeeded)
> ```
> 
> Regards,
> Slaven

**Comment by mohawk2** [comment]
This needs some "approx equals" attention.

**Comment by devel-chm** [comment]
t/pdl_from_string.t has fails because it uses == rather than approx= to compare things like PI and E

**Comment by mohawk2** [comment]
This was closed on SF  2016-10-08.
