### ISSUE TITLE
make Makefile.PL consumable to linux vendors

### ISSUE THREAD

**Issue by kentfredric** [PDLPorters/pdl#139]
Presently, for a human to read Makefile.PL is an impenetrable mass of confusion.

And working out even what has changed since some ancient version is even more confusion.

A handful of things are very much unclear how they work for a downstream packager, requiring substantial cognitive investment ( for which provides copious scope to make mistakes ):
1. Which C-based dependencies are optional?
2. Which perl-based dependencies are optional?
3. How are they optional?
4. Which dependencies are strictly needed for testing and can be avoided if tests will not be performed? 

These questions are all very hard to answer for me reviewing the Makefile.PL, and the file DEPENDENCIES gives little insight

This problem is additionally compounded by the fact META.json currently exposes all testing requirements as "build" requirements, which conveys the notion that they _must_ be installed _even if tests will not be run_

https://metacpan.org/source/CHM/PDL-2.013/META.json#L23

Though this mistake is probably something wrong in the release process because they're declared right in Makefile.PL

( I'm in the process of attempting to upgrade gentoo from the previous version we had, which was 2.4.11, which is now relatively ancient because our "report things out of date" tool has apparently been broken for several years, and its kinda depressing :/ )

**Comment by mohawk2** [comment]
@kentfredric It seems the build vs test requires thing is now fixed? https://metacpan.org/source/CHM/PDL-2.018_01/META.json#L73
