### ISSUE TITLE
Travis-CI for longlong-double-fix branche (temporarily)

### ISSUE THREAD

**Issue by kmx** [PDLPorters/pdl#141]
Could you please temporarily enable Travis on longlong-double-fix branche. It passes all tests for me but I am not able to test it on all PDL environments that you have configured on Travis.

**Comment by mohawk2** [comment]
Could you please make a new branch eg lldf-kmx and work on that? Also, if you were going to copy the existing branch and make further changes, you need to not use merge commits but instead rebase.

If you have done that, then you can pull-request (aka PR) your new branch, and it will then get CI-ed.

**Comment by kmx** [comment]
Ad rebase: I know that it is preferred to rebase instead of merge but this branch (longlong-double-fix) has at least Chris on his computer. I am not very advanced git user but rebase would mean to `git push --force` that means rewriting branch history which is perhaps not a good idea providing that the branch is not only mine, or not? Anyway longlong-double-fix branche is still kind of  experimenting/testing area and IMO all the changes should be in the end squashed into one commit before going to master, therefore I do not see merging master to longlong-double-fix (= polluting longlong-double-fix commit history) as a big issue.

Ad PR: I have now PDL repo cloned from sf.net What's the easiest way to create github PR? Should I create a separate git fork/clone from github?

**Comment by kmx** [comment]
The trick with github pull request did the tring, closing. Thanks.
