### ISSUE TITLE
Travis-CI with at least one older perl

### ISSUE THREAD

**Issue by kmx** [PDLPorters/pdl#143]
I would like to propose to add one older perl (say 5.14) to Travi-CI configuration. Couple of minutes ago I was dealing with a failure due to using av_top_index which is available in 5.17.9+

Not a big deal just a suggestion.

**Comment by zmughal** [comment]
We have Perl v5.10 in the tests. This is the minimum supported Perl for PDL. Is this OK?

The only reason we commented out the versions Perl v5.{12,14,16,18} is because it slows down the whole Travis-CI considerably.

**Comment by kmx** [comment]
You are right now I see it. Closing.
