### ISSUE TITLE
use PDL::Lite; only loads functions for first package it is called in

### ISSUE THREAD

**Issue by shawnlaffan** [PDLPorters/pdl#146]
Using PDL::Lite in more than one package only imports pdl and the other standard functions in the first package it is called from.  

Code to reproduce is below.  

The code works if  ```use PDL::Lite``` is replaced with with ```use PDL``` or ```use PDL::LiteF```, or if ```pdl()``` is set using a glob.

If a ```use PDL::Lite``` is put before the first package declaration then neither sub call works.  

Tested on StrawberryPerl 5.20, pdl 2.012 and pdl 2.013.  

Regards,
Shawn.

```perl
package mk1 {
    use PDL::Lite;

    sub x {
        return pdl (1..10);
    }
}

package mk2 {
    use PDL::Lite;
    #*pdl = \&PDL::Core::pdl;  #  uncomment and the code works
    sub x {
        return pdl (11..20);
    }
}

print mk1::x, "\n";  #  [1 2 3 4 5 6 7 8 9 10]
print mk2::x, "\n";  #  Undefined subroutine &mk2::pdl called at xx.t line 21.
```

**Comment by mohawk2** [comment]
Hi @shawnlaffan, may I suggest you close this and reopen on https://github.com/PDLPorters/pdla-core ? You can PR a failing test / fix and it will be released within hours or days, not months.

**Comment by shawnlaffan** [comment]
Issue ported across.
