### ISSUE TITLE
SF#397 PDL::FFT not 64bit integer safe (and more)

### ISSUE THREAD

**Issue by devel-chm** [PDLPorters/pdl#147]
For complete 64bit index support we'll need to ensure that all the existing modules do the right thing when computing with large PDL_Indx offsets.  This is specifically a problem for code that assumes that an int is the largest integer data type.  TODO:
- write test to determine if 64bit safe
- add runtime checks with warnings/die if too big values are passed to non-supporting routine
- convert to support PDL_Indx type (can handle either 32bit or 64bit depending on platform)

It would be nice if we could implement a common check routine that could be added to the relevant modules.

**Comment by devel-chm** [comment]
Aside from the automatic warnings on out-of-range inputs, the initial focus for the 64bit PDL_Indx support will be in the Basic and Core modules.

**Comment by mohawk2** [comment]
PDL::FFT needed a couple of `int` changed to `size_t`. A more serious problem was its lack of thread-safety due to global `malloc`-ed memory-chunks, but C99 variable-length arrays (or with `factorize`, just pass it a stack-allocated fixed-size array) fixed it.
