### ISSUE TITLE
incorporate Test::PDL into distribution

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#16]
https://github.com/ebaudrez/Test-PDL, https://github.com/PDLPorters/Test-PDL

**Comment by zmughal** [comment]
Discussion from February 2015: <http://comments.gmane.org/gmane.comp.lang.perl.pdl.devel/6266>

**Comment by mohawk2** [comment]
Does this really need to be added to PDL::Core? If not, let's just leave it living separately (albeit recommended, if we do)?

**Comment by mohawk2** [comment]
Since the general direction of travel is towards less in each distro, not more, I will close this. If anyone disagrees, they can reopen!
