### ISSUE TITLE
Take ideas from throughout docs and turn them into GH issues

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#17]
- [x] https://github.com/PDLPorters/pdl/blob/master/Known_problems
- [x] https://github.com/PDLPorters/pdl/wiki/GSoC-2012-Ideas
- [x] https://github.com/PDLPorters/pdl/wiki/Roadmap
- [x] https://github.com/PDLPorters/pdl/wiki/PDL-way-forward-draft
- [x] https://github.com/PDLPorters/pdl/wiki/PDL-TODO-List
- [x] https://github.com/PDLPorters/pdl/blob/master/TODO
- [x] https://sourceforge.net/p/pdl/feature-requests/
- [x] https://sourceforge.net/p/pdl/patches/

**Comment by mohawk2** [comment]
@zmughal could you ticklist this and bring up to date?

**Comment by zmughal** [comment]
I shall

**Comment by mohawk2** [comment]
All done. I've also deleted the noted files / wiki pages as they are thereby obsolete.
