### ISSUE TITLE
PDL module which enables extra sanity checks

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#175]
e.g., 
- enable the checking on `sclr`

Something like `PDL::Strict`. We should check for other such opportunities and add them to the module as time passes.

What do you think?

**Comment by mohawk2** [comment]
I can't think of any sanity-checks (apart from the eternal problem of bounds-checking) that we could even implement, never mind turn on. Can you help me with examples?

**Comment by zmughal** [comment]
The only example I had at the time was to default to `barf` by default for `sclr`:

```perl
      PDL->sclr({Check => 'barf'}); # croak if called with multi-el pdls
```

I opened the issue in hopes of getting ideas for more places where extra checking could be done. I would be thinking an API based on `Devel::StrictMode` like `MooX::Should`.

**Comment by mohawk2** [comment]
I'd have thought that `sclr` on a multi-elt pdl is simply an error, and should just barf anyway? Basically, I'm not seeing the benefit of non-strict mode; either these things are right, or they're not.

**Comment by zmughal** [comment]
That's fair. I don't have any other examples yet. `sclr` is more about API correctness.
