### ISSUE TITLE
which() warning about operator precedence

### ISSUE THREAD

**Issue by stphnlyd** [PDLPorters/pdl#213]
For example, below code gives warning `Possible precedence problem on bitwise | operator`

```perl
use strict;
use warnings;
use PDL::LiteF;
my $a = sequence(5);
which($a < 1 | $a > 3);
```

I know I can suppress it by `no warnings 'precedence';`, but is there any better ways?

**Comment by zmughal** [comment]
The only way outside of disabling the warning is to add extra parentheses so that Perl knows that you meant to write the code that way:

```perl
which( ( $a < 1 ) | ( $a > 3 ) );
```

**Comment by mohawk2** [comment]
Am I missing something? I see that warning as a good thing, and indeed that one should use parens. If one wants to suppress it, `no warnings` is how. @stphnlyd Thoughts?

**Comment by stphnlyd** [comment]
Thanks @zmughal, @mohawk2 ! I am new to PDL, and I've not been using bitwise operator in Perl for long that the parentheses thing did not come to my mind. And you know R's which() method does not require parens in this case. I think this ticket can be closed now, but I wonder if it could be better to add an example to which() in PDL::Primitive, so that people like me can just figure it out.

**Comment by mohawk2** [comment]
@stphnlyd You're probably right about the example. PRs welcome :-) I'll close this issue.
