### ISSUE TITLE
SF#418 warp2d and fitwarp2d polynomial fitting doesn't work as expected

### ISSUE THREAD

**Issue by mohawk2** [PDLPorters/pdl#219]
@d-lamb writes:

As reported by @drzowie on the pdl-general list April 15, 2016:

> Has anyone used the PDL::Image2D methods warp2d and fitwarp2d lately? I dusted it off to prove a point, and I’m finding that fitwarp2d/warp2d appears to not actually work. Warp2d seems to resample images just fine, but the fitted polynomial (or warp2d’s implementation of it) doesn’t come close to matching even quite simple transformations…

A minimal (non-)working example would be helpful. If I were placing bets, I would bet there is a problem with the `_svd` routine in Image2D, though I have not actually examined the code.

the `*warp2d` methods also need to have tests added.

https://sourceforge.net/p/pdl/bugs/418/

**Comment by d-lamb** [comment]
Fixed in 2.019.
