### ISSUE TITLE
SF#439 Output type of 'cat' based on first element of input

### ISSUE THREAD

**Issue by mohawk2** [PDLPorters/pdl#225]
@d-lamb writes:

The output type of `cat` is explicitly set to the type of the first piddle in the input list. Instead, the output should be set to the piddle of the highest type. That change is currently on the `cat_return_type` branch in git and will be merged into master once all tests pass. This ticket is filed for ease of assembling the next release notes.

https://sourceforge.net/p/pdl/bugs/439/

**Comment by d-lamb** [comment]
Fixed in 2.019.
