### ISSUE TITLE
ExtUtils::F77 distribution support

### ISSUE THREAD

**Issue by forskning** [PDLPorters/pdl#247]
Slackware 14.0 (32-bit)
Perl 5.16.1
ExtUtils-F77-1.20

The module which lists these reverse dependencies doesn't support Slackware linux.

Distributions Which Depend on ExtUtils::F77

Photonic
Module::Build::Pluggable::Fortran
Statistics::Lmoments
PDL::IO::Nifti
PDL::Opt::QP
Astro::SLA
PGPLOT
Math::Lsoda
 
http://nurmi-labs.blogspot.com/2018/05/pdl.html

**Comment by mohawk2** [comment]
@forskning What would you like the PDL maintainers to actually do with/about this?

**Comment by forskning** [comment]
Admittedly there haven't been many platform or distribution related issues submitted on the tracker.

The present ExtUtils::F77 limitation of a functioning installation on certain Linux distributions might feasibly as information be of interest to current or future users of other CPAN modules which it is a dependency for, i.e., those other than PDL.

In submitting the issue my intention was more informative rather than any actual request to the PDL developers.

**Comment by karlglazebrook** [comment]
The information is useful, patches would be more so

- Karl

**Comment by forskning** [comment]
https://github.com/PDLPorters/extutils-f77/commit/a89ae7eb5aeb63a56fd5d3026f07fc48f778c055#diff-0d2e0dafe4749ba471b58519c30217e4

gfortran g77 ordering switch

the module should now work for Slackware >=9.0

various other (circa 2018) minor changes to F77.pm, Makefile.PL, and t/require.t

the README was rewritten, inspired by Nokubi Takatsugu (野首貴嗣)

@karlglazebrook made the commits, and uploaded the new v1.21 release to CPAN
