### ISSUE TITLE
Need to update website with GitHub links

### ISSUE THREAD

**Issue by d-lamb** [PDLPorters/pdl#251]
The contents of the "Develop" section of the sidebar and some pages need attention in order to point people to the GitHub issues tracker and not the legacy SourceForge site.  Otherwise we will continue to receive bug reports at the old site.

The website and its associated git repository is still hosted at SourceForge.  I'm OK with that for now, as I haven't found a way to get pdl.perl.org hosted at GitHub while still retaining that url.

**Comment by mohawk2** [comment]
I agree with this. I think it's worth a bit of time from the community to spruce up the public face of PDL?

**Comment by forskning** [comment]
http://pdl.perl.org/?page=credits

See the list of PDL team members.

the hyperlink on the preceding text could be changed from 

https://sourceforge.net/p/pdl/wiki/Team/

to

https://github.com/PDLPorters/pdl/wiki/Team

**Comment by forskning** [comment]
http://pdl.perl.org/?page=install

I suppose the preceding page could mention A. Kennedy's portable PDL edition 

http://strawberryperl.com/releases.html

**Comment by forskning** [comment]
http://pdl.perl.org/?page=users

On Google Chrome 49.0.2623.75 it pops up a window with the text as follows.

Google
Denne side kan ikke indlæse Google Maps korrekt.
Do you own this website? OK

Translation from Danish: "This page cannot read Google Maps correctly."

https://www.aao.gov.au/local/www/jbh/ttf/
Page not found

http://www.journals.uchicago.edu/AJ/journal/
404 NOT FOUND

http://pdl.perl.org/www.emep.int

EMEP

the hyperlink to the preceding should be

http://www.emep.int/

not

http://pdl.perl.org/www.emep.int

http://www.emep.int/reports/2004/Country_Reports

Not Found

The requested URL /reports/2004/Country_Reports was not found on this server.

Apache/2.2.22 (Ubuntu) Server at www.emep.int Port 80

http://www.latuv.uva.es/modisql

Pagina no encontrada: http://www.latuv.uva.es/modisql

http://www.rtve.es/tve/teletexto/500/548_0001.htm

TELETEXTO TVE	548.1		
	%PAGE%

http://www.jonaskaplan.com/perlfmri.html

Not Found

The requested URL /perlfmri.html was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by d-lamb** [comment]
thanks for the broken link reports.  I have some changes "in the cooker" that mention Strawberry Perl Portable, so that will come soon.

**Comment by d-lamb** [comment]
Links updated or removed.  SPP+PDL mentioned.  Thanks for the comprehensive report.  These changes are maintenance only, not a major overhaul.

**Comment by mohawk2** [comment]
@d-lamb Thanks for this! Can you share somewhere (maybe here) how such changes are made?

**Comment by d-lamb** [comment]
@mohawk2 It's a bit legacy.  See the table at http://pdl.perl.org/?page=develop .

AFAIK GitHub won't accept custom VHOSTS so we can't host pdl.perl.org here (the project has had that domain for over 20 years so I'm reluctant to let it go).  So that part of the project is hosted at Sourceforge still.  SF hosts the [PDL-WWW git repo](https://sourceforge.net/p/pdl/pdl-www/ci/master/tree/).

The instructions for pushing changes to pdl.perl.org are on the [GH](https://github.com/PDLPorters/pdl/wiki/Developer's-Corner#modifying-the-website) and [SF](https://sourceforge.net/p/pdl/wiki/Developer%27s_Corner/#modifying-the-website) wikis in the Developer's Corner.
