### ISSUE TITLE
compilation on 5.2.0-1-MANJARO fails

### ISSUE THREAD

**Issue by ng0177** [PDLPorters/pdl#263]
Invalid key WITH_PLPLOT found in user supplied /var/tmp/pamac-build-user/perl-pdl-git/src/perldl.conf
  - this key appears to be no longer in use.
  Please review configuration options and check the comments in
  the file perldl.conf that came with this distribution
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by mohawk2** [comment]
That key does not exist in the CPAN or Git versions of `perldl.conf`. It seems likeliest to have been added by you, or someone else? How are you trying to install PDL?

**Comment by ng0177** [comment]
The package manager of manjaro/arch retrieves
https://aur.archlinux.org/packages/perl-pdl-git/.

It compiles to an extend and then fails. When repeated, then this message
is issued. I attach perldl.conf.

BTW, I am looking for a Linux environment in which pdl> demo 3d works but
haven't seen one. Any suggestions? Thanks!

Preparing...
Cloning perl-pdl-git build files...
Checking perl-pdl-git dependencies...

Building perl-pdl-git...
==> Making package: perl-pdl-git 20180505.4503-1 (So 09 Jun 2019 20:03:11
CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating perl-pdl git repo...
Fetching origin
  -> Found perldl.conf
==> Validating source files with md5sums...
    perl-pdl ... Skipped
    perldl.conf ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of perl-pdl git repo...
Cloning into 'perl-pdl'...
done.
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...

INFORMATION: using file
/var/tmp/pamac-build-user/perl-pdl-git/src/perldl.conf to set configuration
defaults

Invalid key WITH_PLPLOT found in user supplied
/var/tmp/pamac-build-th6mas/perl-pdl-git/src/perldl.conf
  - this key appears to be no longer in use.
  Please review configuration options and check the comments in
  the file perldl.conf that came with this distribution
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by mohawk2** [comment]
It seems to me that Manjaro has broken PDL, and only Manjaro can fix it. If you do `cpanm PDL` to get it from CPAN, or even clone the GitHub repo, it ought to work. There is literally nothing that the PDLPorters can do to help you.

**Comment by ng0177** [comment]
I used cpan install PDL

but then I get this error - pgplot is precisely what I need...
...
t/pgplot.t ...................... skipped: PDL::Graphics::PGPLOT not
installed
t/physical.t .................... skipped: Disabled

**Comment by mohawk2** [comment]
Let's start again. Exactly what are you doing that triggers the error you're seeing? If the steps I would need to take to also see it on my system include installing Manjaro, then you need to talk to the Manjaro people, because I can't help.

**Comment by ng0177** [comment]
You are right: cpan i pdl works seemless under Ubuntu which I tried now.
However, demo 3d fails. Any advice?

pdl> demo 3d
Undefined subroutine &PDL::Demos::TriD1::run called at /usr/bin/perldl line
453, <DATA> line 90.
 at /usr/bin/perldl line 453, <DATA> line 90.
main::demo("3d") called at (eval 63) line 4
main::__ANON__() called at /usr/bin/perldl line 719
eval {...} called at /usr/bin/perldl line 719
main::eval_and_report("demo '3d'\x{a}") called at /usr/bin/perldl line 655
main::process_input() called at /usr/bin/perldl line 675
eval {...} called at /usr/bin/perldl line 675

**Comment by mohawk2** [comment]
I'm afraid I've never actually run a demo yet! I do intend to rework how they operate, within PDLA. If you start by running `cpanm PDLA::Rest`, and then running `perldla`, and try the 3d demo. Then tell me what results you see?

**Comment by ng0177** [comment]
th6mas@freckleHP:~$ cpanm PDLA::Rest
--> Working on PDLA::Rest
Fetching http://www.cpan.org/authors/id/E/ET/ETJ/PDLA-Rest-2.019106.tar.gz
... OK
==> Found dependencies: PDLA::Core
--> Working on PDLA::Core
Fetching http://www.cpan.org/authors/id/E/ET/ETJ/PDLA-Core-2.019107.tar.gz
... OK
Configuring PDLA-Core-2.019107 ... OK
Building and testing PDLA-Core-2.019107 ... OK
Successfully installed PDLA-Core-2.019107
Configuring PDLA-Rest-2.019106 ... OK
Building and testing PDLA-Rest-2.019106 ... OK
Successfully installed PDLA-Rest-2.019106
2 distributions installed
th6mas@freckleHP:~$ pdla
perlDL shell v1.357
 PDLA comes with ABSOLUTELY NO WARRANTY. For details, see the file
 'COPYING' in the PDLA distribution. This is free software and you
 are welcome to redistribute it under certain conditions, see
 the same file for details.
ReadLines, NiceSlice, MultiLines  enabled
Reading PDLA/default.perldlrc...
Found docs database
/home/th6mas/perl5/lib/perl5/x86_64-linux-gnu-thread-multi/PDLA/pdladoc.db
Type 'help' for online help
Type 'demo' for online demos
Loaded PDLA v2.019107 (supports bad values)

Note: AutoLoader not enabled ('use PDLA::AutoLoader' recommended)

pdla> demo 3d
Undefined subroutine &PDLA::Demos::TriD1::run called at
/home/th6mas/perl5/bin/perldla line 451.
 at /home/th6mas/perl5/bin/perldla line 451.
main::demo("3d") called at (eval 53) line 4
main::__ANON__() called at /home/th6mas/perl5/bin/perldla line 717
eval {...} called at /home/th6mas/perl5/bin/perldla line 717
main::eval_and_report("demo '3d'\x{a}") called at
/home/th6mas/perl5/bin/perldla line 653
main::process_input() called at /home/th6mas/perl5/bin/perldla line 673
eval {...} called at /home/th6mas/perl5/bin/perldla line 673

pdla>

**Comment by devel-chm** [comment]
For the PDL 3d demo to run, you will need to have the OpenGL module installed.

**Comment by ng0177** [comment]
I will try later and let you know. Questions: 1) do I need to reinstall PDL
from CPAN because of a major update during the last few day? 2) I noticed a
difference between running "cpan i pdl" and "cpanm PDL" - which one is
correct and what is the difference?

**Comment by ng0177** [comment]
OK, I work now under Ubuntu 18.04 and have OpenGL together with NVIDIA
drivers installed. I followed these steps:

install build-essential
install libpgplot

install cpanminus
cpanm --sudo PDL

install pdl
pdl

but get the below error. Any advice? Thanks!

user@machine:~$ pdl
perlDL shell v1.357
 PDL comes with ABSOLUTELY NO WARRANTY. For details, see the file
 'COPYING' in the PDL distribution. This is free software and you
 are welcome to redistribute it under certain conditions, see
 the same file for details.
ReadLines, NiceSlice, MultiLines  enabled
Reading PDL/default.perldlrc...
Found docs database
/usr/local/lib/x86_64-linux-gnu/perl/5.26.1/PDL/pdldoc.db
Type 'help' for online help
Type 'demo' for online demos
Loaded PDL v2.019 (supports bad values)

Note: AutoLoader not enabled ('use PDL::AutoLoader' recommended)

pdl> demo 3d
Undefined subroutine &PDL::Demos::TriD1::run called at
/usr/local/bin/perldl line 453, <DATA> line 90.
 at /usr/local/bin/perldl line 453, <DATA> line 90.
main::demo("3d") called at (eval 60) line 4
main::__ANON__() called at /usr/local/bin/perldl line 719
eval {...} called at /usr/local/bin/perldl line 719
main::eval_and_report("demo '3d'\x{a}") called at /usr/local/bin/perldl
line 655
main::process_input() called at /usr/local/bin/perldl line 675
eval {...} called at /usr/local/bin/perldl line 675

**Comment by devel-chm** [comment]
I don't see where you installed the OpenGL perl module.
What does the command at the bash shell 'perl -MOpenGL\ 10' do?
On my install I get:

 > perl -MOpenGL\ 10
 > OpenGL version 10 required--this is only version 0.7.
 > BEGIN failed--compilation aborted.

which shows that version 0.7 is installed.

--Chris

**Comment by ng0177** [comment]
Yes, indeed I had to install libopengl-perl but still fails, see below.
Thanks.

user@machine:~$ perl -MOpenGL\ 10
OpenGL version 10 required--this is only version 0.7.
BEGIN failed--compilation aborted.

user@machine:~$ pdl
perlDL shell v1.357
 PDL comes with ABSOLUTELY NO WARRANTY. For details, see the file
 'COPYING' in the PDL distribution. This is free software and you
 are welcome to redistribute it under certain conditions, see
 the same file for details.
ReadLines, NiceSlice, MultiLines  enabled
Reading PDL/default.perldlrc...
Found docs database
/usr/local/lib/x86_64-linux-gnu/perl/5.26.1/PDL/pdldoc.db
Type 'help' for online help
Type 'demo' for online demos
Loaded PDL v2.019 (supports bad values)

Note: AutoLoader not enabled ('use PDL::AutoLoader' recommended)

pdl> demo 3d
Undefined subroutine &PDL::Demos::TriD1::run called at
/usr/local/bin/perldl line 453, <DATA> line 90.
 at /usr/local/bin/perldl line 453, <DATA> line 90.
main::demo("3d") called at (eval 60) line 4
main::__ANON__() called at /usr/local/bin/perldl line 719
eval {...} called at /usr/local/bin/perldl line 719
main::eval_and_report("demo '3d'\x{a}") called at /usr/local/bin/perldl
line 655
main::process_input() called at /usr/local/bin/perldl line 675
eval {...} called at /usr/local/bin/perldl line 675

**Comment by devel-chm** [comment]
One possibility is that you have multiple versions of
PDL installed which is resulting in version skew in
some paths which could break things.  You could try
building and testing a local copy of PDL and then
trying the demos from there.

 From the cpan shell I do:

%cpan
cpan> test PDL
....
.. assuming the build and tests go ok ..
....

cpan> look PDL  # This starts a shell in the build directory
~/.cpan/build/PDL-2.019-0 $ perl -Mblib perldl

pdl> demo
....
.. should get a list of demos here ..
....

pdl> demo 3d    # does this work here?

You could also use the find command to look for
multiple PDL/ folders on your drives.

HTH,
Chris

**Comment by ng0177** [comment]
pdl> demo 3d    # does this work here?

yes, it does - first time! How would you suggest to proceeded?

Thanks, Thomas

**Comment by devel-chm** [comment]
Remove the extra PDL installs and then install from the clean build.
Running  a find command on your linux system looking for directory PDL/ and
files pdl , perldl , and pdl2 should get you started.

**Comment by ng0177** [comment]
I installed WSL Ubuntu, followed the below procedure and everything
surprisingly works! Thanks again for your help, Thomas

ubuntu (pgplot only works under ubuntu)

build-essential

libpgplot-perl

libopengl-perl

freeglut3-dev

pdl

cpan (better!)

$cpan

cpan> install CPAN

cpan> reload cpan

cpan> test PDL

cpan> install PDL
