### ISSUE TITLE
gcc libquadmath: compilation fails on Strawberry perl 5.28 and later

### ISSUE THREAD

**Issue by amba** [PDLPorters/pdl#265]
Compilation fails with Strawberry Perl 5.28 and later with the error below.
The linker complains about missing libquadmath function "libquadmath_snprintf".
The full log for different versions of SP is here:
https://ci.appveyor.com/project/amba/appveyortest/builds/25958295

"C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libquadmath.a" "C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libgfortran.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libm.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libmoldname.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libkernel32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libuser32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libgdi32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libwinspool.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libcomdlg32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libadvapi32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libshell32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libole32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\liboleaut32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libnetapi32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libuuid.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libws2_32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libmpr.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libwinmm.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libversion.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libodbc32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libodbccp32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libcomctl32.a" -Wl,--enable-auto-image-base
C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libgfortran.a(write.o):(.text$get_precision+0x160): undefined reference to `quadmath_snprintf'
C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libgfortran.a(write.o):(.text$get_float_string+0x16b): undefined reference to `quadmath_snprintf'
C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libgfortran.a(write.o):(.text$get_float_string+0xa02): undefined reference to `quadmath_snprintf'
C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libgfortran.a(write.o):(.text$get_float_string+0x1576): undefined reference to `quadmath_snprintf'
C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libgfortran.a(write.o):(.text$get_float_string+0x15fb): undefined reference to `quadmath_snprintf'
collect2.exe: error: ld returned 1 exit status
gmake[2]: *** [Makefile:462: ..\..\blib\arch\auto\PDL\Slatec\Slatec.xs.dll] Error 1
gmake[2]: Leaving directory 'C:/Users/appveyor/.cpanm/work/1563043747.2920/PDL-2.019/Lib/Slatec'
gmake[1]: *** [Makefile:496: subdirs] Error 2
gmake[1]: Leaving directory 'C:/Users/appveyor/.cpanm/work/1563043747.2920/PDL-2.019/Lib'
gmake: *** [Makefile:547: subdirs] Error 2
! Installing PDL failed. See C:\Users\appveyor\.cpanm\work\1563043747.2920\build.log for details. Retry with --force to force install it.
FAIL
7 distributions installed

g++ Slatec.def -o ..\..\blib\arch\auto\PDL\Slatec\Slatec.xs.dll -mdll -s -L"C:\STRAWB~1\perl\lib\CORE" -L"C:\STRAWB~1\c\lib" Slatec.o slatec/chfcm.o  slatec/chfdv.o  slatec/chfev.o  slatec/chfie.o  slatec/d1mach.o  slatec/dasum.o  slatec/daxpy.o  slatec/dchfcm.o  slatec/dchfdv.o  slatec/dchfev.o  slatec/dchfie.o  slatec/ddot.o  slatec/dgeco.o  slatec/dgedi.o  slatec/dgefa.o  slatec/dgesl.o  slatec/dp1vlu.o  slatec/dpchbs.o  slatec/dpchce.o  slatec/dpchci.o  slatec/dpchcm.o  slatec/dpchcs.o  slatec/dpchdf.o  slatec/dpchfd.o  slatec/dpchfe.o  slatec/dpchia.o  slatec/dpchic.o  slatec/dpchid.o  slatec/dpchim.o  slatec/dpchkt.o  slatec/dpchsp.o  slatec/dpchst.o  slatec/dpchsw.o  slatec/dpcoef.o  slatec/dpoco.o  slatec/dpodi.o  slatec/dpofa.o  slatec/dpolft.o  slatec/dscal.o  slatec/dswap.o  slatec/ezfft1.o  slatec/ezfftb.o  slatec/ezfftf.o  slatec/ezffti.o  slatec/fdump.o  slatec/i1mach.o  slatec/idamax.o  slatec/isamax.o  slatec/j4save.o  slatec/pchbs.o  slatec/pchce.o  slatec/pchci.o  slatec/pchcm.o  slatec/pchcs.o  slatec/pchdf.o  slatec/pchfd.o  slatec/pchfe.o  slatec/pchia.o  slatec/pchic.o  slatec/pchid.o  slatec/pchim.o  slatec/pchkt.o  slatec/pchsp.o  slatec/pchst.o  slatec/pchsw.o  slatec/pcoef.o  slatec/polfit.o  slatec/pvalue.o  slatec/pythag.o  slatec/r1mach.o  slatec/radb2.o  slatec/radb3.o  slatec/radb4.o  slatec/radb5.o  slatec/radbg.o  slatec/radf2.o  slatec/radf3.o  slatec/radf4.o  slatec/radf5.o  slatec/radfg.o  slatec/rfftb.o  slatec/rfftb1.o  slatec/rfftf.o  slatec/rfftf1.o  slatec/rs.o  slatec/sasum.o  slatec/saxpy.o  slatec/sdot.o  slatec/sgeco.o  slatec/sgedi.o  slatec/sgefa.o  slatec/sgesl.o  slatec/snrm2.o  slatec/spoco.o  slatec/spodi.o  slatec/spofa.o  slatec/srot.o  slatec/srotg.o  slatec/sscal.o  slatec/ssvdc.o  slatec/sswap.o  slatec/tql2.o  slatec/tqlrat.o  slatec/tred1.o  slatec/tred2.o  slatec/xerbla.o  slatec/xercnt.o  slatec/xerhlt.o  slatec/xermsg.o  slatec/xerprn.o  slatec/xersve.o  slatec/xgetua.o    "C:\STRAWB~1\perl\lib\CORE\libperl528.a"
"C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libquadmath.a" "C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libgfortran.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libm.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libmoldname.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libkernel32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libuser32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libgdi32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libwinspool.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libcomdlg32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libadvapi32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libshell32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libole32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\liboleaut32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libnetapi32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libuuid.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libws2_32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libmpr.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libwinmm.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libversion.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libodbc32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libodbccp32.a" "C:\STRAWB~1\c\x86_64-w64-mingw32\lib\libcomctl32.a" -Wl,--enable-auto-image-base
C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libgfortran.a(write.o):(.text$get_precision+0x160): undefined reference to `quadmath_snprintf'
C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libgfortran.a(write.o):(.text$get_float_string+0x16b): undefined reference to `quadmath_snprintf'
C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libgfortran.a(write.o):(.text$get_float_string+0xa02): undefined reference to `quadmath_snprintf'
C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libgfortran.a(write.o):(.text$get_float_string+0x1576): undefined reference to `quadmath_snprintf'
C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libgfortran.a(write.o):(.text$get_float_string+0x15fb): undefined reference to `quadmath_snprintf'
collect2.exe: error: ld returned 1 exit status
gmake[2]: *** [Makefile:462: ..\..\blib\arch\auto\PDL\Slatec\Slatec.xs.dll] Error 1
gmake[2]: Leaving directory 'C:/Users/appveyor/.cpanm/work/1563043747.2920/PDL-2.019/Lib/Slatec'
gmake[1]: *** [Makefile:496: subdirs] Error 2
gmake[1]: Leaving directory 'C:/Users/appveyor/.cpanm/work/1563043747.2920/PDL-2.019/Lib'
gmake: *** [Makefile:547: subdirs] Error 2
! Installing PDL failed. See C:\Users\appveyor\.cpanm\work\1563043747.2920\build.log for details. Retry with --force to force install it.
FAIL
7 distributions installed

**Comment by amba** [comment]
This seems to be related with the latest version 1.23 of ExtUtils::F77, which is used in Strawberry Perl 5.28.2.1 and 5.30.0.1.
I was able to build PDL on those by downgrading ExtUtils::F77:

```
$ cpanm ExtUtils::F77@1.22
$ cpanm PDL
```

**Comment by mohawk2** [comment]
@amba Could I ask you to copy/paste the respective command lines generated under EU::F77 versions 1.22 and 1.23? (or even better, just say what are the differences)

**Comment by amba** [comment]
The difference is the order of libquadmath.a and libgfortran.a on the linker command.
EU::F77 1.22: `"C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libgfortran.a" "C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libquadmath.a"`
EU::F77 1.23: `"C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libquadmath.a" "C:\strawberry\c\bin\..\lib\gcc\x86_64-w64-mingw32\7.1.0\libgfortran.a" `

There is a ticket in EU::F77: https://rt.cpan.org/Public/Bug/Display.html?id=129356

**Comment by amba** [comment]
I also opened a ticket for Strawberry Perl:
https://rt.cpan.org/Public/Bug/Display.html?id=130070

**Comment by mohawk2** [comment]
May I suggest that asking distros to downgrade module versions is a long way from a good idea.

I have applied @kmx's patch to EU::F77, where the problem actually lies. Someone with permissions needs to either release it, or give me permissions to do so.

In the meantime, this is not actually a PDL-caused or -fixable problem. May I therefore suggest closing this issue?

**Comment by amba** [comment]
Hey, I completely agree that a new release of EU::F77 would be the best solution.
