### ISSUE TITLE
Perl 5.14+ "x" operator change means overload needs "scalar" (from Known_problems)

### ISSUE THREAD

**Issue by mohawk2** [PDLPorters/pdl#268]
A change in perl-5.14 on how the 'x' operator works affects PDL's overload of that operator for matrix multiplication.  This can affect code using parentheses to group.  An example  that shows the problem is code like:

     f( ($pdl0 * $pdl1) x $pdl2 )

which now gives an error.  The fix is to force the element-wise operation in parentheses to be treated in scalar context rather than list context.  E.g.,

    f( scalar($p0 * $p1) x $p2 );

**Comment by zmughal** [comment]
I have found the commit that made that change <https://github.com/Perl/perl5/commit/6f1401dc2acd2a2b85df22b0a74e5f7e6e0a33aa>. I do not see a way around this other than to document it as a breaking change and the above fix (either by using `scalar` or calling `matmult` directly).
