### ISSUE TITLE
failed CPAN install: t/07-grid.t "sequence" is not exported by the PDL::Lite module

### ISSUE THREAD

**Issue by rloiselle** [PDLPorters/pdl#271]
CPAN version: 2.2011
Linux CentOS 7 
kernal 3.10.0-862.14.4.el7.x86_64
perl v5.16.3

 PDL-NDBin-0.018]$ make test

PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/00-compile.t ................... ok
t/00-report-prereqs.t ............ #
# Versions for all modules listed in MYMETA.json (including optional ones):
#
# === Configure Requires ===
#
#     Module              Want  Have
#     ------------------- ---- -----
#     ExtUtils::MakeMaker  any  7.38
#     PDL::Core::Dev       any undef
#
# === Build Requires ===
#
#     Module              Want Have
#     ------------------- ---- ----
#     ExtUtils::MakeMaker  any 7.38
#
# === Test Requires ===
#
#     Module               Want     Have
#     ------------------- ----- --------
#     ExtUtils::MakeMaker   any     7.38
#     File::Spec            any     3.40
#     IO::Handle            any     1.33
#     IPC::Open3            any     1.12
#     Module::Pluggable     3.1      4.8
#     PDL                 2.004    2.019
#     PDL::Types            any    undef
#     Test::Deep            any    1.128
#     Test::Exception       any     0.43
#     Test::More            any 1.302169
#     Test::NoWarnings      any     1.04
#     Test::PDL            0.10     0.14
#     blib                 1.01     1.06
#
# === Test Recommends ===
#
#     Module         Want     Have
#     ---------- -------- --------
#     CPAN::Meta 2.120900 2.143240
#
# === Runtime Requires ===
#
#     Module           Want  Have
#     ---------------- ---- -----
#     Carp              any  1.26
#     Class::Load       any  0.25
#     Data::Dumper      any 2.145
#     Exporter          any  5.68
#     List::MoreUtils   any 0.428
#     List::Util        any  1.27
#     Log::Any          any 1.707
#     Math::Round       any  0.07
#     PDL::Lite         any undef
#     POSIX             any  1.30
#     Params::Validate  any  1.29
#     UUID::Tiny        any  1.04
#     XSLoader          any  0.24
#     integer           any  1.00
#     strict            any  1.07
#     warnings          any  1.13
#
t/00-report-prereqs.t ............ ok
t/01-bad.t ....................... ok
t/02-actions.t ................... ok
t/03-iterator.t .................. ok
t/04-flatten.t ................... ok
t/05-oo.t ........................ ok
t/06-functions.t ................. ok
t/07-grid.t ...................... "sequence" is not exported by the PDL::Lite module
Can't continue after import errors at usr/perl5/lib/perl5/x86_64-linux-thread-multi/PDL/Exporter.pm line 64.
BEGIN failed--compilation aborted at t/07-grid.t line 8.
# Looks like your test exited with 255 before it could output anything.
t/07-grid.t ...................... Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 12/12 subtests

Test Summary Report
-------------------
t/07-grid.t                    (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 12 tests but ran 0.
Files=14, Tests=568,  4 wallclock secs ( 0.10 usr  0.02 sys +  2.49 cusr  0.51 csys =  3.12 CPU)
Result: FAIL
Failed 1/14 test programs. 0/568 subtests failed.
make: *** [test_dynamic] Error 255

**Comment by mohawk2** [comment]
You're probably better off putting "```" before and after the console output, as that makes it actually readable.

This looks quite a lot like you're having a problem with PDL::NDBin, which is not controlled by us, but by @ebaudrez. I suggest you close this and open an issue on https://github.com/ebaudrez/PDL-NDBin/issues

**Comment by rloiselle** [comment]
Thank you!
