### ISSUE TITLE
export chkform optionally in PDL::IO::Pic

### ISSUE THREAD

**Issue by wlmb** [PDLPorters/pdl#277]
PDL::IO::Pic has a nice internal routine 'chkform' to obtain the kind of image given the file name. Together with rpiccan, it can help to decide if an image can be read or not, thus avoiding failures. It woud be useful to optionally export this routine.

**Comment by d-lamb** [comment]
As mentioned on the pdl-general mailing list, 'chkform' is unlikely to disappear because it's been in PDL for over 20 years.  However, a pull request that included some documentation for the function would be sufficient to get it added to the `@EXPORT_OK` list of functions.

**Comment by wlmb** [comment]
I tried to do that. Added an exportable function with a different name
(imageformat) copying the style from other functions of the package to
give access to the internal chkform, added some explanation and an
example and made a pull request.

Thanks and regards,
Luis



On Tue, May 19, 2020 at 09:53:04PM -0700, Derek Lamb wrote:
> As mentioned on the pdl-general mailing list, 'chkform' is unlikely to disappear because it's been in PDL for over 20 years.  However, a pull request that included some documentation for the function would be sufficient to get it added to the `@EXPORT_OK` list of functions.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/PDLPorters/pdl/issues/277#issuecomment-631235176

--

                                                                  o
W. Luis Mochán,                      | tel:(52)(777)329-1734     /<(*)
Instituto de Ciencias Físicas, UNAM  | fax:(52)(777)317-5388     `>/   /\
Apdo. Postal 48-3, 62251             |                           (*)/\/  \
Cuernavaca, Morelos, México          | mochan@fis.unam.mx   /\_/\__/
GPG: 791EB9EB, C949 3F81 6D9B 1191 9A16  C2DF 5F0A C52B 791E B9EB
