### ISSUE TITLE
PDL::GSL::INTERP supports extrapolation when GSL>=1.15 does not

### ISSUE THREAD

**Issue by d-lamb** [PDLPorters/pdl#279]
Yury Pakhomov reported on the pdl-general mailing list that PDL::GSL::INTERP was returning NaN's when used for extrapolation.  This is due to an change introduced in GSL 1.15 that "The interpolation functions now return NaN " …  "when x is out of range, instead of extrapolating." (see [the GSL NEWS file](http://git.savannah.gnu.org/cgit/gsl.git/tree/NEWS).)  [This GSL mailing list thread](https://lists.gnu.org/archive/html/help-gsl/2011-12/msg00024.html) and the links there show the change and the train of thought.

Clearly PDL::GSL::INTERP needs to be updated to reflect this reality: extrapolation should not be permitted if GSL version is >=1.15.  Or we could just remove the extrapolation option.

This code shows the error:
```perl
$x=sequence(9)*0.5;
$y=pdl(qw( 0.555  0.566  0.567  0.567  0.569  0.572  0.577  0.584 0.591));

$spl=PDL::GSL::INTERP->init('akima',$x,$y);

$xx=sequence(11)*0.5;
$yy=$spl->eval($xx,{Extrapolate=>1});

print $yy;
[0.555 0.566 0.567 0.567 0.569 0.572 0.577 0.584 0.591 NaN NaN]
```

**Comment by mohawk2** [comment]
Given the module is definitely about *interpolation*, is there a reason for it to do *extrapolation*? If not, we can just delete that.

**Comment by d-lamb** [comment]
Not really a good reason.  PDL::Func handles extrapolation.  (Oddly, GSL handles extrapolation, too, but only for 2D.)

I think I even went as far deleting all the extrapolation stuff, but never got around to committing it.  Will do that and link it here presently.
