### ISSUE TITLE
Proj4 version 6 incompatibility

### ISSUE THREAD

**Issue by mohawk2** [PDLPorters/pdl#283]
As of version 6.0.0 of the Proj library, `ACCEPT_USE_OF_DEPRECATED_PROJ_API_H` must be defined in order to use `proj_api.h`. `Devel::CheckLib` currently provides no way to supply `#define`s.

**Comment by zmughal** [comment]
What about using `-DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1` or `/DACCEPT_USE_OF_DEPRECATED_PROJ_API_H=1` in [`ccflags`](https://metacpan.org/pod/release/MATTN/Devel-CheckLib-1.14/lib/Devel/CheckLib.pm#ccflags) or create a temporary header file that has:

```c
#define ACCEPT_USE_OF_DEPRECATED_PROJ_API_H 1
#include "proj_api.h"
```

**Comment by zmughal** [comment]
Related https://github.com/PDLPorters/pdl/issues/230

**Comment by shawnlaffan** [comment]
proj_api.h has been completely removed in version 8, which is the current release.  
https://github.com/OSGeo/PROJ/blob/master/NEWS

PDL depends on Alien::Proj4 for this reason, so maybe it could ensure it only gets libs from that source?  (I have not looked at the relevant code yet).

**Comment by mohawk2** [comment]
@shawnlaffan As of 2.038 PDL only uses the CPAN Alien::Proj4, which works. However, this is imperfect as e.g. Debian won't want to make a Perl package for Alien::Proj4. What is needed is "just" to update PDL::GIS::Proj so it works with Proj 8.

If anyone wants to volunteer, that's great! Or, if you have insight into the relevant changes between Proj versions 4 and 8 and can save time for whoever does dig into this by sharing that insight, that will also be amazing.

**Comment by shawnlaffan** [comment]
I had not considered the Debian issue.

I would suggest modifying the PDL code to use something like [Geo::LibProj::FFI](https://metacpan.org/pod/Geo::LibProj::FFI).  Its bindings are not complete yet, but might be enough for what PDL uses.  The FFI::Platypus interface means it is relatively simple to extend.  

I've not tried using Geo::LibProj::FFI, but it does depend on [Alien::proj](https://metacpan.org/pod/Alien::proj), which I maintain.  

More generally, the GDAL bindings were moved to an FFI interface a while ago and work well.  https://metacpan.org/pod/Geo::GDAL::FFI

**Comment by mohawk2** [comment]
I think that using C code is a known route, whereas using FFI will require some learning. But the biggest obstacle is the API point, since it seems like to have changed. Given the fairly straightforward stuff the PDL modules use Proj for, do you know of any "gotchas" that you can help me steer around? :-)

**Comment by shawnlaffan** [comment]
I think the coordinate definitions have changed, so much of the code munging might go wrong.  PDL should be able to use EPSG codes directly instead of what it seems to do now in the various transforms.  

I also have vague memories of axis orders changing in some cases (lat/long instead of long/lat), but that issue will come to light pretty quickly.  

The other thing to bear in mind is how much this is used in practice.  A check for the module name on https://grep.metacpan.org/ gives no results, and the same for PDL::Transform::Proj4.  That still leaves the darkpan, though.

**Comment by shawnlaffan** [comment]
EPSG codes can be gleaned from http://epsg.io/

I can help sort out which ones.

**Comment by mohawk2** [comment]
My feeling (and hope) is that it won't be a colossal effort to update from Proj 4 to Proj 8, and that it will be worth it for the number of benefits it brings to PDL; clearing the appearance of neglect, for a start.

Your help is greatly appreciated!

**Comment by mohawk2** [comment]
The info that was needed was at:
- https://proj.org/development/migration.html#function-mapping-from-old-to-new-api
- https://gitlab.kitware.com/vtk/vtk/-/merge_requests/5582/diffs for the new `pj_get_list_refs()`

As soon as https://github.com/shawnlaffan/perl-alien-proj/pull/6 is merged and released then (hopefully) we can merge the `proj6` branch changes on `devops` and PDL.

**Comment by mohawk2** [comment]
There are some surprising (to me) numerical difference on MacOS 11 (only) which make `t/proj_transform2.t` fail. Excerpt:

```
2021-12-12T15:57:40.4304750Z #   Failed test 'check ref_ortho for slices[0]'
2021-12-12T15:57:40.4313330Z ##[error]#   at t/proj_transform2.t line 75.
2021-12-12T15:57:40.4315630Z #          got: '
2021-12-12T15:57:40.4315980Z # [
2021-12-12T15:57:40.4316380Z #  [118 118 118 118 118 118 118 118 118 118]
2021-12-12T15:57:40.4316820Z #  [119 119 119 119 119 119 119 119 119 119]
2021-12-12T15:57:40.4317250Z #  [119 119 119 119 119 119 119 119 119 119]
2021-12-12T15:57:40.4317680Z #  [120 120 120 120 120 120 120 120 120 120]
2021-12-12T15:57:40.4318120Z #  [120 120 120 120 120 120 120 120 120 120]
2021-12-12T15:57:40.4318560Z #  [121 121 121 121 121 121 121 121 121 121]
2021-12-12T15:57:40.4319000Z #  [121 121 121 121 121 121 121 121 121 121]
2021-12-12T15:57:40.4319450Z #  [122 122 122 122 122 122 122 122 122 122]
2021-12-12T15:57:40.4319870Z #  [122 122 122 122 122 122 122 122 122 122]
2021-12-12T15:57:40.4320310Z #  [122 122 122 122 122 122 122 122 122 122]
2021-12-12T15:57:40.4320660Z # ]
2021-12-12T15:57:40.4321350Z # '
2021-12-12T15:57:40.4322090Z #     expected: '
2021-12-12T15:57:40.4322470Z # [
2021-12-12T15:57:40.4322850Z #  [118 118 118 118 118 118 118 118 118 118]
2021-12-12T15:57:40.4323290Z #  [119 119 119 119 119 119 119 119 119 119]
2021-12-12T15:57:40.4323730Z #  [119 119 119 119 119 119 119 119 119 119]
2021-12-12T15:57:40.4324240Z #  [120 120 120 120 120 120 120 120 120 120]
2021-12-12T15:57:40.4324700Z #  [120 120 120 120 120 120 120 120 120 120]
2021-12-12T15:57:40.4325120Z #  [121 121 121 121 121 121 121 121 121 121]
2021-12-12T15:57:40.4325560Z #  [121 121 121 121 121 121 121 121 121 121]
2021-12-12T15:57:40.4326000Z #  [121 121 121 121 121 121 121 121 121 121]
2021-12-12T15:57:40.4326430Z #  [122 122 122 122 122 122 122 122 122 122]
2021-12-12T15:57:40.4326870Z #  [122 122 122 122 122 122 122 122 122 122]
2021-12-12T15:57:40.4327230Z # ]
2021-12-12T15:57:40.4327900Z # '
```

Note the third from last row has different values!

**Comment by mohawk2** [comment]
@juddtaylor The commit that changes from PROJ.4 to v6: https://github.com/PDLPorters/pdl/commit/e755d9cb881b9873f5a8e511feb41942b99f86e8, and see above the links I mentioned on IRC in case your needs are a bit more details.

I will now close this issue since it is fixed!

**Comment by mohawk2** [comment]
After the next CPAN release of PDL, we should submit an update to https://proj.org/development/bindings.html that includes PDL!

**Comment by shawnlaffan** [comment]
Thanks for sorting this one out.

**Comment by mohawk2** [comment]
Most welcome! And if you can install the latest `master` version and try it out (and report problems), that would be great!

**Comment by juddtaylor** [comment]
I will say one thing, although EPSG codes are the way things are done now, the proj definition strings allow you to create custom projections that aren't in EPSG databases. I commonly an orthographic with the origin defined as the satellite ground system location. In other software like geoserver step 1 is always "create a custom EPSG projection with a bogus number" then you can use that to build referencing/reprojections. Limiting a proj API to only EPSG numbers loses you a lot of functionality/flexibility.

**Comment by juddtaylor** [comment]
Also, wow, looking at code you wrote that's almost old enough to drink makes you feel things. Sheesh.

**Comment by shawnlaffan** [comment]
> I will say one thing, although EPSG codes are the way things are done now, the proj definition strings allow you to create custom projections that aren't in EPSG databases.

Proj still supports WKT2, WKT and a few other formats to define coordinate systems.  Details are at https://proj.org/development/reference/cpp/cpp_general.html?highlight=wkt2#general_doc_1standards
