### ISSUE TITLE
pdl2 blows up with Devel::REPL but without a role module

### ISSUE THREAD

**Issue by mohawk2** [PDLPorters/pdl#294]
```
$ cpanm Devel::REPL
# worked
$ pdl2
Failed to load role: Devel::REPL::Plugin::Interrupt Can't locate Sys/SigAction.pm in @INC (you may need to install the Sys::SigAction module) (@INC contains: PERLBREW/libs/perl-5.32.0@normal/lib/perl5/x86_64-linux PERLBREW/libs/perl-5.32.0@normal/lib/perl5 PERLBREW/perls/perl-5.32.0/lib/site_perl/5.32.0/x86_64-linux PERLBREW/perls/perl-5.32.0/lib/site_perl/5.32.0 PERLBREW/perls/perl-5.32.0/lib/5.32.0/x86_64-linux PERLBREW/perls/perl-5.32.0/lib/5.32.0) at PERLBREW/libs/perl-5.32.0@normal/lib/perl5/Devel/REPL/Plugin/Interrupt.pm line 9.
```

**Comment by zmughal** [comment]
`Devel::REPL` uses `optional_features` from the meta spec [here for plugin prereqs](https://metacpan.org/source/ETHER/Devel-REPL-1.003028/META.yml#L49), so if we want to support all [these plugins by default](https://github.com/PDLPorters/pdl/blob/2.025/Perldl2/Profile/Perldl2.pm#L14-L33), we need to also add their prereqs.

**Comment by zmughal** [comment]
By the way, Sys::SigAction is POSIX only.

**Comment by mohawk2** [comment]
It seems like you understand this stuff well; if you could spell out more info on how to fix this easily, that would be really helpful. Even more helpful: making a pull-request ;-)

**Comment by mohawk2** [comment]
This was in fact super-easy once I grasped you'd linked to the list of things that needed checking!
