### ISSUE TITLE
PDL::GSL::INTEG produces error: Hash given as a pdl - but not {PDL} key!

### ISSUE THREAD

**Issue by systemdlete2** [PDLPorters/pdl#313]
The following code will produce an error:

```
#!/usr/bin/perl

use strict;
use bignum;
use PDL;
use PDL::GSL::INTEG;

#my ($res,$abserr,$ierr) = gslinteg_qagil(\&myfn,1.0,1e-7,0,1000);
# with warnings on
my($res,$abserr,$ierr) = gslinteg_qagil(\&myfn,1.0,1e-7,0,1000,{Warn => 'y'});

sub myfn{
  my ($x) = @_;
  return exp($x);
}

```

The error I get is:

`Hash given as a pdl - but not {PDL} key! at /usr/lib/x86_64-linux-gnu/perl5/5.28/PDL/GSL/INTEG.pm line 426.`

The problem seems to arise because of "use bignum;" -- removing bignum cures the problem.

**Comment by zmughal** [comment]
The transparent `bignum` conflicts with PDL. `bignum` creates a `Math::Big{Int,Float}` instance and passing this into a PDL function confuses the function because it expects a `PDL` instance instead.

So instead, use the ndarray constructor to explicitly create a `PDL` instance: `pdl( $ndarray_specification )`*

* See `pdldoc pdl` for the documentation in [`PDL::Core#pdl`](https://p3rl.org/PDL::Core#pdl).

```perl
#!/usr/bin/perl

use strict;
use PDL;
use PDL::GSL::INTEG;

my (@results_use_bignum, @results_no_bignum);

{
use bignum (); # to avoid conflict with PDL::inf()
my @results_use_bignum = gslinteg_qagil(\&myfn,pdl(1.0),pdl(1e-7),pdl(0),pdl(1000),{Warn => 'y'});
}

{
no bignum;
my @results_no_bignum = gslinteg_qagil(\&myfn,pdl(1.0),pdl(1e-7),pdl(0),pdl(1000),{Warn => 'y'});
}

use Test::PDL;
use Test::More;

is_deeply \@results_use_bignum, \@results_no_bignum, 'are the same';
done_testing;

sub myfn{
  my ($x) = @_;
  return exp($x);
}
```

**Comment by zmughal** [comment]
I believe that there could be a more useful diagnostic message here. It should print out the `ref` of the SV passed in so that it is clear that what is being processed is not intelligible to PDL.

**Comment by mohawk2** [comment]
Thanks for looking into this! Clearly we need a change with a test, and making the message clearer.

**Comment by zmughal** [comment]
Now a better error message is given in <https://github.com/PDLPorters/pdl/commit/cd6ceb0ab2ece56d4aa88ece6c9958615cb1d9e6>. @mohawk2++.

What kind of test are you looking for?

**Comment by mohawk2** [comment]
The test in `t/croak.t` I added seemed adequate. If everyone's happy, we can close this? I'll be releasing this change very soon.
