### ISSUE TITLE
PDL::IO::GD Makefile.PL still uses perldl.conf

### ISSUE THREAD

**Issue by d-lamb** [PDLPorters/pdl#316]
This should be a pretty easy fix, but I ran out of time.  Adding the last line in this chunk to IO/GD/Makefile.PL expands the search of include paths to include those entries of the Perl's 'cppflags' that start with "-I".  There probably should be a way to add in "INC" entries passed to the top-level Makefile.PL to further expand this list.

~~~perl
my @inc_locations = (
    '/usr/include',
    '/usr/local/include',
    $Config{usrinc},
    map{s/^-I//;$_}(grep /^-I/,split(/ /, $Config{cppflags})),
);
~~~
There's some logic in the rest of that Makefile.PL about when to build and when not to build, that probably also should be cleaned up to reflect the deprecated $PDL::Config.

**Comment by mohawk2** [comment]
Thanks for the report! I'll leave the `WITH_GD` stuff alone for now, but as you say it will be removed in due course.
