### ISSUE TITLE
IO/Storable.pm: syntax error (croak not defined) due to misplaced use Carp;

### ISSUE THREAD

**Issue by viy2** [PDLPorters/pdl#317]
use Carp; should be after package declaration
proposed patch:

```diff
--- PDL-2.051/IO/Storable/storable.pd	2021-04-27 03:19:28.000000000 +0000
+++ PDL-2.051/IO/Storable/storable.pd	2021-06-18 17:55:42.460311085 +0000
@@ -90,10 +90,10 @@
 
 pp_addpm << 'EOPM';
 
-use Carp;
 
 { package # hide from PAUSE
     PDL;
+use Carp;
 # routines to make PDL work with Storable >= 1.03
 
 # pdlpack() serializes an ndarray, while pdlunpack() unserializes it. Earlier
```

**Comment by viy2** [comment]
found in PDL-2.051

**Comment by mohawk2** [comment]
Thanks! I've updated your original text by putting `` ```diff `` and `` ``` `` around the patch parts to make GH get the highlighting right. (Today I learned that to get `` ` `` characters in as literals, you need to surround them with \`\`  and \`\`, and I gave up figuring out to get pairs of \` as literals)
