### ISSUE TITLE
PDL::PP and xs: Code is not inside a function error

### ISSUE THREAD

**Issue by fantasma13** [PDLPorters/pdl#318]
Hi
I've come across this error in a number of modules which used to compile fine against earlier versions of PDL, I think up to 2.025. Now, with 2.050/51, I see this error:

Code is not inside a function (maybe last function was ended by a blank line  followed by a statement on column one?) in XXXX.xs line YYYY.

Affected modules are at least
PDL::IO::Matlab
PDL::Fit::Levmar
PDL::Drawing::Prima - I could resolve the issue there.

It seems to be related to white space in code strings like
pp_addxs, pp_addboot

where C or XS code is passed on.

**Comment by mohawk2** [comment]
I have just installed very latest PDL (2.051) and successfully built and tested current PDL::IO::Matlab. Can you confirm which versions of Perl, PDL, and the modules mentioned above you are trying, and give error messages?

**Comment by fantasma13** [comment]
This seems to be resolved in version 2.052. 

For completeness, perl: v5.32.1 built for x86_64-linux-gnu-thread-multi
PDL::IO::Matlab 0.005
PDL::Fit::Levmar 0.0100

**Comment by mohawk2** [comment]
> This seems to be resolved in version 2.052.
> 
> For completeness, perl: v5.32.1 built for x86_64-linux-gnu-thread-multi
> PDL::IO::Matlab 0.005
> PDL::Fit::Levmar 0.0100

Thank you for the confirmation, and the report!
