### ISSUE TITLE
t/gsl_linalg.t fails on mips64el & mipsel

### ISSUE THREAD

**Issue by sebastic** [PDLPorters/pdl#336]
The pdl Debian package fails to build on mips64el & mipsel due to a test failure:
```
#   Failed test at t/gsl_linalg.t line 48.
# got:-0.07329228-0.07329228i
# expected:-0.07329228-8.64040000000001e-11i
# Looks like you failed 1 test of 5.
```
Full build logs: [mips64el](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=mips64el&ver=1%3A2.057-1&stamp=1630505109&raw=0), [mipsel](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=mipsel&ver=1%3A2.057-1&stamp=1630507237&raw=0)

**Comment by mohawk2** [comment]
Thanks for the report! I've had another look at the `.pd` file, and there's nothing that looks like it might cause this. Does Debian make a package for https://metacpan.org/dist/Math-GSL? The only thing I can think of is that `GSL_IMAG` is misbehaving on MIPS, but I can't see how it would.

**Comment by sebastic** [comment]
> Does Debian make a package for https://metacpan.org/dist/Math-GSL?

Yes: https://tracker.debian.org/pkg/libmath-gsl-perl

The pdl packages doesn't use it though, it builds with libgsl-dev.

**Comment by mohawk2** [comment]
Interestingly, https://ci.debian.net/packages/libm/libmath-gsl-perl/ shows no results for MIPS. Is it possible this is actually a GSL problem? Do you have any advice? I'm a bit lost as to how to proceed.

**Comment by sebastic** [comment]
> Is it possible this is actually a GSL problem?

That's possible, it was recently updated from 2.6 to 2.7, and this update causes regression in libmath-gsl-perl & ruby-gsl:

 https://tracker.debian.org/pkg/gsl

The libmath-gsl-perl issue is also related to linalg:

 https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=993324

**Comment by mohawk2** [comment]
My feeling based on the above is that the MIPS build of pdl might need to either stay broken, or have a temporary fix of disabling either that test, or PDL::GSL::LINALG, on MIPS?

I'm not seeing anything there that can be sanely fixed on the PDL side?

**Comment by sebastic** [comment]
The package was already updated to ignore test failures on these two architectures.

While I'd rather not keep doing that, spending more effort on these architectures may not be warranted.

**Comment by mohawk2** [comment]
It's not my preference either, but this seems like a problem created by GSL. If there's nothing to be done here, are you content to close this? :-(

**Comment by sebastic** [comment]
Not really, but let's spend our time on something else.
