### ISSUE TITLE
CPAN install of PDL, change in Inf, bad value handling

### ISSUE THREAD

**Issue by yelnats** [PDLPorters/pdl#338]
I know there have been quite a few changes recently to standardize the BAD value handling in PDL. Is the following change in output between default installed versions of PDL an expected result or issue?

perl -we 'use PDL; $a=(pdl(1)/pdl(0))->setnantobad->setbadtoval(0); print $a,"\n";'

VERSION: PDL v2.019
Results in 0

VERSION: PDL v2.057
Results in Inf

**Comment by zmughal** [comment]
This change seems to have happened with <https://github.com/PDLPorters/pdl/commit/d01eaf3518e8285034e62b1132403b7dfeda1ff5> which switched from using [`isfinite()`](https://www.gnu.org/software/libc/manual/html_node/Floating-Point-Classes.html#index-isfinite) to `isnan()`.

This occurred between PDL 2.039 and PDL 2.040:

```sh
$ cpm install -g PDL@2.039; perl -MPDL -E 'say ( (pdl(1)/pdl(0))->setnantobad )'
DONE install PDL is up to date. (2.039)
0 distribution installed.
BAD

$ cpm install -g PDL@2.040; perl -MPDL -E 'say ( (pdl(1)/pdl(0))->setnantobad )'
DONE install PDL-2.040 (using prebuilt)
1 distribution installed.
Inf
```

@mohawk2? The commit above does not match the documentation. It should be `isfinite()` again (even though the name should probably be `setnonfinitetobad`).

**Comment by zmughal** [comment]
@mohawk2, you addressed this here https://github.com/PDLPorters/pdl/commit/a002950419c6e88d0a883c5e0a4a508ecb37ef95 by changing the docs.

That's fine but may break code. If we're going to do that, we *NEED* to provide an alternative that does the same using a `!isfinite( ... )` macro and prominently say when it changed and what to use instead.

**Comment by mohawk2** [comment]
@zmughal To address your point, I regard the change for 2.040 as a bug-fix. It should have been better-documented as a change, and I will update the Changes file to show it did for that version.

**Comment by zmughal** [comment]
Does `setbadif` work inplace? The original semantics are a common enough operation that an inplace way of doing things is important to have.

**Comment by mohawk2** [comment]
> Does `setbadif` work inplace? The original semantics are a common enough operation that an inplace way of doing things is important to have.

Agree it's important to have. `setbadif` poses problems working inplace because the flag gets unset too early. I've made a `setnonfinitetobad` which works inplace, in 5987520.

I tweaked `copy` earlier this year (169f7a75cd0e6e91fe2918d79835cf8bc82ff9b5) to make it behave in a way that seemed more useful. I think inplace will benefit from more thought - should it stay on until it's turned off?

**Comment by mohawk2** [comment]
@yelnats To answer your original question explicitly, rather than by implication above: the change in behaviour was deliberate, and the gap in capability it creates is closed with the new function (albeit it's only on `master` not released yet). Does this resolve the issue for you?

**Comment by yelnats** [comment]
Yes, thanks for closing the gap in capability. I believe the new function resolves my issue.

**Comment by mohawk2** [comment]
Great! You can install from GitHub `master` using cpanm, but as noted above there won't be a CPAN release for a little longer. If you feel the issue is resolved, are you content to close the issue?

**Comment by yelnats** [comment]
Yes, that will get my by until the next release, thanks.
