### ISSUE TITLE
Missing function "setinftobad"

### ISSUE THREAD

**Issue by alex-prusevich** [PDLPorters/pdl#340]
Dear developers of PDL,

The latest version on Github has a new function:
**setnonfinitetobad** - converts both **Inf** and **NaN** to BAD.

The other function relevant to this type of conversions is
**setnantobad** - converts only **NaN** to BAD

So, it is logical to have this function too-
**setinftobad** - converts only **Inf** to BAD

Can you please consider adding setinftobad to the new version of PDL.
Thanks,
-Alex P.

**Comment by mohawk2** [comment]
> Dear developers of PDL,
> 
> The latest version on Github has a new function:
> **setnonfinitetobad** - converts both **Inf** and **NaN** to BAD.
> 
> The other function relevant to this type of conversions is
> **setnantobad** - converts only **NaN** to BAD
> 
> So, it is logical to have this function too-
> **setinftobad** - converts only **Inf** to BAD
> 
> Can you please consider adding setinftobad to the new version of PDL.
> Thanks,
> -Alex P.

Dear Alex,

Your wish has been granted! (It's now on `master` and will shortly be getting dev-released as it's about time)

Yours sincerely,
Developers of PDL

**Comment by mohawk2** [comment]
I have just released PDL 2.057_01. Please report any problems! (preferably on a new issue)

**Comment by alex-prusevich** [comment]
Thanks a lot!
-Alex P.
