### ISSUE TITLE
PP code with variable I in Pars expands to imaginary number

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#344]
This gives very confusing error messages from the C compiler. This should
either be fixed or give a warning during code generation time.

**Comment by zmughal** [comment]
@juddtaylor (hopefully the right account!), this issue has been addressed for Pars and OtherPars named `I`.

Maybe another pass later on can use `perl -V:cpprun` to find other `#define`s as you mentioned as long as it doesn't slow down the build too much.

**Comment by mohawk2** [comment]
The `cpprun` idea sounds like it would be fragile and I would need *a lot* of persuading that it would nevertheless be a good idea ;-)

**Comment by juddtaylor** [comment]
Great job guys! This fix is good enough for me. I only mentioned cpprun test expanding variable names as a potential for over-engineering things. I'm not sure I believe all that much in it myself at this point.

**Comment by mohawk2** [comment]
Thanks for the feedback!
