### ISSUE TITLE
undefined symbol: VSwrite + Vsetname

### ISSUE THREAD

**Issue by eserte** [PDLPorters/pdl#373]
The test suite fails on RedHat-like systems (that is: centos6, centos7, and fedora28). On centos6 it looks like this:
```
Can't load '/home/cpansand/.cpan/build/2019042109/PDLA-IO-HDF-2.019100-0/blib/arch/auto/PDLA/IO/HDF/VS/VS.so' for module PDLA::IO::HDF::VS: /home/cpansand/.cpan/build/2019042109/PDLA-IO-HDF-2.019100-0/blib/arch/auto/PDLA/IO/HDF/VS/VS.so: undefined symbol: Vsetname at /opt/perl-5.22.3/lib/5.22.3/x86_64-linux/DynaLoader.pm line 193.
```
On centos7 and fedora28 it's:
```
Can't load '/home/cpansand/.cpan/build/2019042107/PDLA-IO-HDF-2.019100-4/blib/arch/auto/PDLA/IO/HDF/VS/VS.so' for module PDLA::IO::HDF::VS: /home/cpansand/.cpan/build/2019042107/PDLA-IO-HDF-2.019100-4/blib/arch/auto/PDLA/IO/HDF/VS/VS.so: undefined symbol: VSwrite at /opt/perl-5.28.1/lib/5.28.1/x86_64-linux/DynaLoader.pm line 193, <DATA> line 207.
```

**Comment by mohawk2** [comment]
Thank you to all who took a look at this!

I had another look at this just now. On my Ubuntu system, the libraries are linked in the same order as Slaven shows (the "mfh" one first). That library (with `nm -D`) refers to e.g. `VSwrite` (with a `U` flag), which is defined in the one without "mfh" in.

I logged into a CentOS 7 machine, ran:
```shell
sudo yum install epel-release # a package repo with HDF
sudo yum install hdf-devel
cpanm Alien::HDF4
```
then configured latest `master` version of PDL. Then these commands:
```
make coretest
make basictest # the HDF tests need at least IO::Misc
(cd IO/HDF/; make test)
```

They passed. Unfortunately I cannot reproduce the issue, so I will close. If more information comes to light, please reopen!
