### ISSUE TITLE
t/proj_transform.t fails (fedora)

### ISSUE THREAD

**Issue by eserte** [PDLPorters/pdl#380]
On all my fedora smokers (various perl versions) t/proj_transform.t fails. Sample fail report: http://www.cpantesters.org/cpan/report/99ede01a-807d-11ec-be14-c8621f24ea8f
Full list of linux reports (fail reports for 2.072 are not yet): http://matrix.cpantesters.org/?dist=PDL%202.069;os=linux;reports=1

**Comment by mohawk2** [comment]
Thanks! This is partly due to a change in behaviour of PROJ >6.3.1 (2.072 has diagnostics to show which version of PROJ it's running), but all those 255s look like they might be an error. Hopefully the extra diagnostics will help track this down.

**Comment by mohawk2** [comment]
By the way, one of your smokers shows a PDL::NDBin failure (http://www.cpantesters.org/cpan/report/c171787c-83f7-11ec-9614-2a2c1f24ea8f) looks like Perl is finding the `site_perl` PDL (with core version 12) while the module was built against 2.072 with core version 20 (the latest). The `@INC` looks correct in that the second-to-top shows a PDL-2.072. Worth an investigate?

**Comment by eserte** [comment]
This was a little bit harder, but I think the investigation has a result. Problem is the compilation:
```
cc -c  "-I/opt/perl-5.26.3/lib/site_perl/5.26.3/x86_64-linux/PDL/Core"  -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2   -DVERSION=\"\" -DXS_VERSION=\"\" -fPIC "-I/opt/perl-5.26.3/lib/5.26.3/x86_64-linux/CORE"   Actions_PP.c
```
`-I` points to the old installed version of PDL, but it should be something like `-I/home/cpansand/.cpan/build/2022020318/PDL-2.072-0/blib/lib/PDL/Core`. Unfortunately CPAN.pm is able to adjust `PERL5LIB` if running in test-only mode without installation. but it does not do any adjustments for `-I` and `-L`.
