### ISSUE TITLE
PDL::IO::IDL error

### ISSUE THREAD

**Issue by YuryPakhomov** [PDLPorters/pdl#381]
I use now PDL 2.072.

#! /usr/bin/perl
use PDL::IO::IDL;
$PDL::IO::IDL::test=1;
$mod = ridl("test.sav");

print (...) interpreted as function at /usr/local/lib64/perl5/PDL/IO/IDL.pm line 681.
Useless use of concatenation (.) or string in void context at /usr/local/lib64/perl5/PDL/IO/IDL.pm line 681.
Found record of type TIMESTAMP...
Seeking 1108 (0 tags read so far...)
Found record of type VERSION...
Warning: IDL file is v12 (neither 5 nor 6); winging it. Check results!
Seeking 1164 (1 tags read so far...)
Found record of type VARIABLE...
Usage: $type->bswap with no args at Basic/Core/Types.pm.PL line 1084.
	PDL::Type::bswap(PDL::Type=ARRAY(0x13cdf30), PDL=SCALAR(0x1cf96f0)) called at /usr/local/lib64/perl5/PDL/IO/IDL.pm line 837
	PDL::IO::IDL::r_n_pdl(0, ARRAY(0x1221c28), PDL::Type=ARRAY(0x13cdf30)) called at /usr/local/lib64/perl5/PDL/IO/IDL.pm line 844
	PDL::IO::IDL::r_n_cast(0, ARRAY(0x1221c28), PDL::Type=ARRAY(0x13cdf30), PDL::Type=ARRAY(0x13cde70)) called at /usr/local/lib64/perl5/PDL/IO/IDL.pm line 471
	PDL::IO::IDL::r_var(HASH(0x1221af0)) called at /usr/local/lib64/perl5/PDL/IO/IDL.pm line 324
	PDL::IO::IDL::read_records(HASH(0x1221af0)) called at /usr/local/lib64/perl5/PDL/IO/IDL.pm line 150
	PDL::IO::IDL::ridl("test.sav") called at test.pl line 4

The same errors were in PDL 2.068. While in PDL 2.057 it works

Found record of type TIMESTAMP...
Seeking 1108 (0 tags read so far...)
Found record of type VERSION...
Warning: IDL file is v12 (neither 5 nor 6); winging it. Check results!
Seeking 1164 (1 tags read so far...)
Found record of type VARIABLE...
Seeking 1216 (2 tags read so far...)
Found record of type VARIABLE...
Seeking 1268 (3 tags read so far...)
Found record of type VARIABLE...
Seeking 1320 (4 tags read so far...)
Found record of type VARIABLE...
Seeking 2336 (5 tags read so far...)
Found record of type VARIABLE...
Reading a structure description...
not predefined. ntags=19..
ntags is 19
narrays=9
nstructs=
finished with structure desc...
Reading 2963 structures....
0 of 2963...
100 of 2963...
200 of 2963...
300 of 2963...
400 of 2963...
500 of 2963...
600 of 2963...
700 of 2963...
800 of 2963...
900 of 2963...
1000 of 2963...
1100 of 2963...
1200 of 2963...
1300 of 2963...
1400 of 2963...
1500 of 2963...
1600 of 2963...
1700 of 2963...
1800 of 2963...
1900 of 2963...
2000 of 2963...
2100 of 2963...
2200 of 2963...
2300 of 2963...
2400 of 2963...
2500 of 2963...
2600 of 2963...
2700 of 2963...
2800 of 2963...
2900 of 2963...
Seeking 10883584 (6 tags read so far...)
Found record of type END_MARKER...
Seeking 0 (7 tags read so far...)

**Comment by YuryPakhomov** [comment]
The diff between these versions is:

 $ diff /usr/lib64/perl5/vendor_perl/PDL/IO/IDL.pm IDL.pm  
106a107,108
> use warnings;
> use PDL::Types;
827c829
<     
---
>     $type = PDL::Type->new($type);
829,831c831
<     my $dsize = PDL::Core::howbig($type);
<     my $hunksize = $dsize * $nelem;
< 
---
>     my $hunksize = PDL::Core::howbig($type->enum) * $nelem;
834d833
<     
837d835
<     
839,846c837
<     
<     
<     if($swab) {
< 	bswap2($pdl) if($dsize==2);
< 	bswap4($pdl) if($dsize==4);
< 	bswap8($pdl) if($dsize==8);
<     }
< 
---
>     $type->bswap($pdl) if $swab;

**Comment by mohawk2** [comment]
Thanks for the report! One problem for the IO::IDL is we don't have tests for it, which is how this slipped through. Could you please attach on here your `test.sav` file so we can turn this into a test-case?

**Comment by mohawk2** [comment]
I hope you don't mind, I've edited your diff with ```diff for ease of reference.

**Comment by YuryPakhomov** [comment]
test.sav 6.5Mb
[test.sav.gz](https://github.com/PDLPorters/pdl/files/7994170/test.sav.gz)

**Comment by mohawk2** [comment]
Thanks for this! Since it would be part of the distribution, could you come up with a representative file that's more like few kilobytes rather than 6MB? I'm happy to construct the test file myself (although if you were able to come up with that too, it would be amazing!).

**Comment by YuryPakhomov** [comment]
I created
[test.sav.gz](https://github.com/PDLPorters/pdl/files/8002622/test.sav.gz)
 the reduced SAV file.

**Comment by mohawk2** [comment]
Thank you! This has just been fixed on `master` and will be released soon. Please give it a go and let us know if it works.

**Comment by mohawk2** [comment]
This has now been released as 2.073. I will close this on the assumption that it all works, but please reopen if I am wrong!
