### ISSUE TITLE
medover produces noisy images

### ISSUE THREAD

**Issue by d-lamb** [PDLPorters/pdl#382]
I have a 3D piddle that is a (x,y,i) collection of images, and I'd like to take the median over the last dimension.  My code looks like this:

```perl
$median = $pdl3d->mv(-1,0)->medover;
```

Typically the images are smooth, but recent PDL versions produce images that are noisy.  Good and bad examples attached.  Of interest, the noise pattern changes if I produce $median again.  (It does not change if I just plot the same image again; only if I call `medover` again.)

I did a git bisect and it tells me

> 960b28000cb855191810dbc8b752bec403709c64 is the first bad commit
commit 960b28000cb855191810dbc8b752bec403709c64
Author: Ed J <mohawk2@users.noreply.github.com>
Date:   Mon Nov 8 04:42:42 2021 +0000
    use online_cpus to set_autopthread_targ if no env var

I'm glad I did bisect because I would have been looking at ufunc.pd to try to figure out the problem!  I can dig some more, or try any suggestions, but thought I'd throw this into the universe to see if it triggers an 'aha!'.

![medover_good](https://user-images.githubusercontent.com/6362944/152561105-c3c793ea-398c-4b67-a156-7b08fe526565.png)
![medover_bad](https://user-images.githubusercontent.com/6362944/152561110-87639558-d090-434f-8f5e-9844e7d17b14.png)

**Comment by mohawk2** [comment]
The online CPUs change means it will be a thread-safety type of issue; are you able to produce a testcase that's a lot smaller but identifiably (to you) noisy post that commit? That will then be a failing test which I can use. Can you try either that new testcase or your existing one with environment var `PDL_AUTOPTHREAD_TARG` set to 1 and see if it's still noisy?

**Comment by mohawk2** [comment]
This is exactly a thread-safety issue, and looking in `Ufunc` reveals the problem: `medover`, like many other functions, has a `[t]` Par. Right now these get allocated for the whole trans, so all the different pthreads will use the same memory, causing chaos.

**Comment by mohawk2** [comment]
Could you have a try with latest `master` version? I've pushed what I hope is a fix.

**Comment by mohawk2** [comment]
This has now been released as 2.073. I will close this on the assumption that it all works, but please reopen if I am wrong!

**Comment by d-lamb** [comment]
This seems to be OK!  My test case to trigger the bug would have been pretty close to what you wrote, so I think that is sufficient.  Thanks for the prompt (and thorough) response.

**Comment by mohawk2** [comment]
Glad to hear it! Thanks for the feedback (and the very-actionable report).
