### ISSUE TITLE
clang12 and perl <5.35.2 generate multitudinous warnings

### ISSUE THREAD

**Issue by d-lamb** [PDLPorters/pdl#390]
This is not a PDL problem, but may come up so I am opening an issue for awareness.  With clang 12 and higher, when compiling PDL, clang generates ~100 warnings per compiled file of the form:

```
In file included from ../../blib/lib/PDL/PP.pm:666:
In file included from /opt/local/lib/perl5/5.28/darwin-thread-multi-2level/CORE/perl.h:5446:
/opt/local/lib/perl5/5.28/darwin-thread-multi-2level/CORE/inline.h:1807:9: warning: '}' and ')' tokens terminating statement expression appear in different macro expansion contexts [-Wcompound-token-split-by-macro]
        CLEAR_ARGARRAY(av);
        ^~~~~~~~~~~~~~~~~~
/opt/local/lib/perl5/5.28/darwin-thread-multi-2level/CORE/cop.h:642:5: note: expanded from macro 'CLEAR_ARGARRAY'
    } STMT_END
    ^
/opt/local/lib/perl5/5.28/darwin-thread-multi-2level/CORE/inline.h:1807:9: note: ')' token is here
        CLEAR_ARGARRAY(av);
        ^~~~~~~~~~~~~~~~~~
/opt/local/lib/perl5/5.28/darwin-thread-multi-2level/CORE/cop.h:642:7: note: expanded from macro 'CLEAR_ARGARRAY'
    } STMT_END
      ^~~~~~~~
/opt/local/lib/perl5/5.28/darwin-thread-multi-2level/CORE/perl.h:532:21: note: expanded from macro 'STMT_END'
#   define STMT_END     )
                        ^
94 warnings generated.
```

This was fixed and merged into Perl blead with https://github.com/Perl/perl5/pull/18984, but lacking any action on our part, this will cause compilation ugliness for quite some time for clang users.  I have not tried blead or 5.35.2 to verify that the warnings are no longer present.  This is not just a Perl problem, as https://github.com/ruby/ruby/pull/4504 shows.

**Comment by mohawk2** [comment]
Thanks! @zmughal Did you have a fix for this already? (as MacOS uses clang)

**Comment by zmughal** [comment]
This is fixed by setting ccflags to `-Wno-compound-token-split-by-macro`. I have a fix that sets it for all EUMM-based modules:

<https://github.com/PDLPorters/devops/pull/35/files#diff-df4d181afbf865bd6a53065fd07c1fd45d323568ec0330a151ce15c14777ae49R170>

Another way to fix it is to build your own Perl after applying this patch <https://github.com/skaji/Devel-PatchPerl-Plugin-FixCompoundTokenSplitByMacro>.

**Comment by mohawk2** [comment]
@d-lamb It looks to me like the above is the only thing we can do in this repo, and therefore there is no further actionable issue here?

**Comment by d-lamb** [comment]
Thanks for the pointer, @zmughal!  Using your code as a guide, I fixed this on the command line.  Included here in case anybody else needs help with the quote maze:

```shell
perl Makefile.PL CCFLAGS="`perl -MConfig -E 'print $Config{ccflags};'` -Wno-compound-token-split-by-macro"
```

**Comment by mohawk2** [comment]
Nice!
