### ISSUE TITLE
IO/STL/t/basic.t failure on s390x (big endian)

### ISSUE THREAD

**Issue by sebastic** [PDLPorters/pdl#394]
The Debian package build for PDL 2.079 failed on s390x due to test failures:
```
make[4]: Entering directory '/<<PKGBUILDDIR>>/IO/STL'
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(1, '../../blib/lib', '../../blib/arch')" t/*.t
	PDL::IO::STL::_read_ascii(GLOB(0x2aa37d74150)) called at /<<PKGBUILDDIR>>/IO/STL/../../blib/lib/PDL/IO/STL.pm line 72
	PDL::rstl("PDL", GLOB(0x2aa37d74150)) called at /<<PKGBUILDDIR>>/IO/STL/../../blib/lib/PDL/IO/STL.pm line 56
	PDL::IO::STL::rstl(GLOB(0x2aa37d74150)) called at t/basic.t line 34
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 2.
t/basic.t .. 
ok 1
ok 2 - wstl error right
Dubious, test returned 255 (wstat 65280, 0xff00)
All 2 subtests passed 

Test Summary Report
-------------------
t/basic.t (Wstat: 65280 Tests: 2 Failed: 0)
  Non-zero exit status: 255
  Parse errors: No plan found in TAP output
Files=1, Tests=2,  0 wallclock secs ( 0.01 usr  0.00 sys +  0.06 cusr  0.00 csys =  0.07 CPU)
Result: FAIL
Failed 1/1 test programs. 0/2 subtests failed.
make[4]: *** [Makefile:623: test_dynamic] Error 255
```
[Full buildlog](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=s390x&ver=1%3A2.079-1&stamp=1651608502&raw=0)

The same test also failed on the non-release architectures: [powerpc](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=powerpc&ver=1%3A2.079-1&stamp=1651609233&raw=0), [ppc64](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=ppc64&ver=1%3A2.079-1&stamp=1651608955&raw=0), [sparc64](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=sparc64&ver=1%3A2.079-1&stamp=1651611724&raw=0)

**Comment by mohawk2** [comment]
Thanks for the report! The message as shown is a bit mysterious because the stack trace stops before it says what is the error message, and the line it's triggered from. That will need fixing.

But the underlying reason is almost certainly that while the reading is careful about reading in network (little-endian) order, the writing is not:https://github.com/PDLPorters/pdl/blob/a4bac40588a7448b3ff4795e23d355fe9fecf67a/IO/STL/STL.pm#L237-L239

**Comment by mohawk2** [comment]
That was indeed the problem. The missing error message was because the message had binary data. Since it wasn't clear what to do about that, I did nothing. This problem is now fixed and will be included in the next release.
