### ISSUE TITLE
hist segmentation fault

### ISSUE THREAD

**Issue by fantasma13** [PDLPorters/pdl#397]
hist( $data, $min, $min, $step) results in segmentation fault.

In other words, min == max is not caught if step is explicitly set. Probably a division by zero? Best in Basic.pm line ~465 ?

Ingo

**Comment by mohawk2** [comment]
```
pdl> hist( $data, $min, $min, $step)
Can't call method "min" on an undefined value at /home/osboxes/pdl-code/blib/lib/PDL/Basic.pm line 457.
```

Please provide the output of `perldl -V` and/or the actual data you used. The above report is so far non-actionable.

**Comment by mohawk2** [comment]
Ok, I have in fact figured what you presumably were trying to get at:

```
pdl> hist(pdl(1,2),0,0,1)
Segmentation fault (core dumped)
```

**Comment by mohawk2** [comment]
Thanks for the report!

Division by 0 does not cause a segmentation fault. The error was the size of the output ndarray was 0, which (in modern PDL) means it had a `NULL` data pointer, so when the routine tried to store results in it, that caused a segmentation fault.
