### ISSUE TITLE
Introducing PDL::Opt::Simplex::Simple

### ISSUE THREAD

**Issue by KJ7LNW** [PDLPorters/pdl#399]
Hello PDL team!

I would like to announce that [PDL::Opt::Simplex::Simple](https://metacpan.org/pod/PDL::Opt::Simplex::Simple) is now available.  It seemed right to name the module in PDL's top-level namespace and I would like to coordinate transparently with your team where it makes sense to do so.  

The [POD](https://metacpan.org/pod/PDL::Opt::Simplex::Simple) gives a good summary, basically it provides name-based variables to the optimization function, plus many other features like:

- Per-variable weights
- Min/max clamps
- Variable-result caching when the input is re-tested by simplex (which actually happens more often then you might expect).
- Variable rounding: each variable can be rounded to a different precision:
   - Round for each iteration to leverage caching if the variable values are nearing their desired precision to speed up optimization.
   - Final result rounding: For example, you may wish to round variables to a precision like 0.001 in the output but leave full precision during the calculation phase.
- Multi-pass `ssize` values.  For example, start coarse and get smaller: `ssize => [1, 0.5, 0.25, 0.1 ]`
   - Even if a previous pass has a better result it will keep the best result if subsequent passes got stock at a minimum.
- Stagnation detection and early exit given a stagnation count and tolerance.
- Future ideas if anyone is interested:
   - The basic framework could work for other optimization algorithms.  For example, were the [Particle Swarm](https://metacpan.org/release/KYLESCH/PSO-0.7/view/lib/PSO.pm) algorithm ported to run under PDL as a single vector passed to the optimize function in the same way that `simplex()` does, then refactor of PDL::Opt::Simplex::Simple could enable the same features above with a bit of subclassing.
   - Multi-dimensional PDLs could be optimized [with some help](https://metacpan.org/pod/PDL::Opt::Simplex::Simple#PDL-variable-considerations)

@zmughal noticed this was posted to CPAN and asked about repo details, so here it is:

 - https://github.com/KJ7LNW/perl-PDL-Opt-Simplex-Simple

**Comment by KJ7LNW** [comment]
Thanks @zmughal!  

I don't have a need to hold the ticket open, feel free to open an issue here if something comes up:

- https://github.com/KJ7LNW/perl-PDL-Opt-Simplex-Simple/issues

**Comment by mohawk2** [comment]
Your module looks very interesting (and implies PDL::Opt::Simplex needs improving for your use-case). The doc says "patches welcome", but doesn't mention the issues link above. The way to make that easiest to find is to add to your Makefile.PL's `WriteMakefile` call a `META_MERGE` key; see for example https://github.com/PDLPorters/pdl/blob/ab5b39bd51d1e6761e6dd2f482cbcc7c68ab368a/Makefile.PL#L200-L211

**Comment by KJ7LNW** [comment]
@mohawk2, thanks I appreciate the feedback. This is my first Perl module published on CPAN with a new PAUSE account so I'm learning the ropes here. The next release will have those changes in Makefile.PL.

**Comment by KJ7LNW** [comment]
and...released!  This addressed the srand issue too.

**Comment by KJ7LNW** [comment]
@mohawk2 , the 1.4 version is up and shows the homepage and repository links at metacpan.

Here are a couple links detailing our original use of the simplex modules for optimizing antenna geometry:
- https://metacpan.org/pod/PDL::Opt::Simplex::Simple#Antenna-Geometry:-Use-an-array-for-the-ssize-parameter-from-coarse-to-fine-perturbation.
- https://github.com/KJ7LNW/xnec2c-optimize

**Comment by mohawk2** [comment]
Great stuff! By the way, I fear that come version 1.10 it may not work right (but I could be wrong). Most modules (see `perldoc perlmodstyle`) use a decimal such as 2.004.

**Comment by KJ7LNW** [comment]
Ya, I noticed that too when trying to release 1.3.1 which showed up as 1.003001  Might have to fix it by bumping to v2, but now I know. sigh.
