### ISSUE TITLE
Problem with building on 32-bit without bad values support.

### ISSUE THREAD

**Issue by eundas** [PDLPorters/pdl#4]
I built on 32-bit without bad values and got this:

Test Summary Report
-------------------
t/pdl_from_string.t       (Wstat: 65280 Tests: 32 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 113 tests but ran 32.
t/ufunc.t                 (Wstat: 0 Tests: 19 Failed: 0)
  TODO passed:   18-19
Files=124, Tests=1297, 16 wallclock secs ( 0.30 usr  0.08 sys +  9.96 cusr  0.88 csys = 11.22 CPU)
Result: FAIL
Failed 1/124 test programs. 0/1297 subtests failed.
make: *** [test_dynamic] Error 255

**Comment by zmughal** [comment]
According to Travis-CI builds, the build still fails tests when compiled without badval support.

From [Build #56.8](https://travis-ci.org/zmughal/p5-PDL/jobs/51672222):
```
Test Summary Report
-------------------
t/fits.t                  (Wstat: 0 Tests: 90 Failed: 0)
  TODO passed:   13, 17, 26, 30, 39, 45, 51, 60
t/inline-comment-test.t   (Wstat: 0 Tests: 3 Failed: 0)
  TODO passed:   3
t/iotypes.t               (Wstat: 0 Tests: 7 Failed: 0)
  TODO passed:   1-7
t/pdl_from_string.t       (Wstat: 65280 Tests: 32 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 113 tests but ran 32.
t/transform.t             (Wstat: 0 Tests: 25 Failed: 0)
  Parse errors: Bad plan.  You planned 27 tests but ran 25.
t/ufunc.t                 (Wstat: 0 Tests: 35 Failed: 0)
  TODO passed:   14-18, 24-35
Files=128, Tests=1668, 27 wallclock secs ( 0.68 usr  0.22 sys + 26.11 cusr  2.88 csys = 29.89 CPU)
Result: FAIL
```

**Comment by mohawk2** [comment]
What does prove -bv say about those tests - where exactly are they failing?

**Comment by mohawk2** [comment]
It's not on master yet, but this fixes the issue which was just test failures: 973537825863718fc5758a0723763c40e50bf3fb

**Comment by mohawk2** [comment]
Now merged. Closing.
