### ISSUE TITLE
Perl long-double builds have a perl<=>pdl scalar rounding error

### ISSUE THREAD

**Issue by KJ7LNW** [PDLPorters/pdl#405]
Is there a way to deal with perl<=>pdl scalar conversion rounding errors when running with perl build with `-Duselongdouble` ?

I'm not sure if the rounding error shows up going from a scalar to PDL or from PDL to scalar.  In either case, I think both PDL and perl with longdouble's can represent 0.001 natively without rounding error, so its just an issue converting between the 80- vs 64-bit doubles:

**With `-Duselongdouble`:**
```perl
perl> $n=0.001
perl> $p=pdl($n)
perl> p $n
0.001
perl> p $p
0.00100000000000000002
perl> p $p->sclr - 0.00000000000000000002
0.001
```

**Without `-Duselongdouble` (ie, normal perl)**
```perl
pdl> $n=0.001
pdl> $p=pdl($n)
pdl> p $n
0.001
pdl> p $p
0.001
pdl> p $p->sclr
0.001
```

I tested `-Duselongdouble` this with `perlbrew` as follows:
```sh
perlbrew -j 60 install -Duselongdouble 5.26.3
perlbrew install-cpanm
perlbrew use 5.26.3
cpanm PDL
pdl
pdl> $profit++
```

**Comment by mohawk2** [comment]
If you are doing floating-point exact comparisons, you are making a mistake. In a sense, the long-double aspect of that is almost a coincidence. This is not a problem that is fixable in PDL, nor in Perl.

**Comment by KJ7LNW** [comment]
Not comparisons exactly, just trying to make sure that the difference between before and after a transform is less than some threshold which I arbitrarily chose as 1e-9.  On normal perl builds, 1e-9 is sufficient but on longdouble builds I needed 1e-8 because of the rounding error.  For  example: http://www.cpantesters.org/cpan/report/5e642b66-04bd-11ed-9fa3-afbd7c3021a8

I "fixed" it in the test code by checking $Config{uselongdouble} and reducing the threshold, but wanted to know if there is a more accurate conversion between types.

**Comment by mohawk2** [comment]
The normal epsilon to use is 1e-6, albeit that is not relative but absolute (which has been the subject of some discussion as we are looking at incorporating Test::PDL into the main PDL distribution, to add relative as well as absolute difference). Your current tests for P:IO:Touchstone are incorrect if they fail with a difference of 1e-9.

**Comment by mohawk2** [comment]
See https://github.com/ebaudrez/Test-PDL/wiki/Rationale:-tolerances for that discussion.

**Comment by KJ7LNW** [comment]
Awesome, great reference.  Thanks for the feedback, I'll set everything to 1e-6 which is still quite small.
