### ISSUE TITLE
.pd files are not indexed on metacpan 

### ISSUE THREAD

**Issue by dk** [PDLPorters/pdl#417]
hi,

I've got a module PDL::PrimaImage on metacpan that could not be found using normal search there, and there's no pod content if you try to read about that module using a direct link https://metacpan.org/release/KARASIK/PDL-PrimaImage-1.02 .

I started therefore to extract .pm and .pod content from the .pd file, and in order to produce just .xs file from the unchanged pp_def's, I found the only way to skip .pm file generation is to prepend  ```$::PDLPACK = 'NONE';``` in the .pd file. This is though not documented so I'm worried how long this hack survives.

Anyway, whether that is a big problem or not, I don't know, but I should very much like to ask how to proceed if I want to 1) having my module properly indexed 2) its pod content could be viewable on metacpan.

Here's my current efforts, unreleased: https://github.com/dk/PDL-PrimaImage

Thank you!

PS: I would propose to add an extra parameter to pp_addpm something like {XS_Only=>1}, if that would make sense

**Comment by mohawk2** [comment]
MetaCPAN still does not index .pd files, but back in 2015 the mighty kmx made PDL's `make dist` add a `GENERATED` directory with all the (author's local versions of) the `.pm` files. See https://github.com/dk/PDL-PrimaImage/pull/1 for the correct way to handle this.

This mechanism is how all the various PDL distros have docs on MetaCPAN for their `.pd` files, such as https://metacpan.org/pod/PDL::Ops - there isn't much documentation spelling this stuff out, but the many examples should make it very easy, or ask here, or on IRC :-)

**Comment by mohawk2** [comment]
To summarise: you absolutely don't need to do any of the things you're proposing in this issue, it's all taken care of. The upload you made back in 2013 didn't have this stuff available.

**Comment by dk** [comment]
Thank you very much for quick reponse! Applied and v1.03 is made and uploaded, and the pod is shown fine. However it's not searchable still, and doesn't show under my list of modules. I guess I give it a day, probably they have some indexing jobs running less often.. but it's still strange that v1.03 shown under /releases, not in /dists as my other modules:  https://metacpan.org/release/KARASIK/PDL-PrimaImage-1.03

**Comment by mohawk2** [comment]
MetaCPAN updates itself periodically rather than as an instant reaction to uploads. In an hour or so it *ought* to look as expected, please check back then.

In the meantime, it seems to me this issue is dealt with, and could be closed? (Though PRs to improve the docs would be most welcome :-)

**Comment by dk** [comment]
yes, at least the docs are visible. Is it okay we continue talking here if, contrary to the expectations, the module still won't be visible?

**Comment by mohawk2** [comment]
> yes, at least the docs are visible. Is it okay we continue talking here if, contrary to the expectations, the module still won't be visible?

Of course! Feel free to speak up on IRC as well. I'd love to know if so, since that would imply quite serious problems across the whole PDL-verse ;-)
