### ISSUE TITLE
should append  complain if output ndarray has wrong shape?

### ISSUE THREAD

**Issue by djerius** [PDLPorters/pdl#445]
PDL 2.084

While rehabilitating the tests for PDL::Primitive,  I came across this behavior:

This works as expected:
```
pdl> $x = zeroes(2); p append(pdl([2]),pdl([3]), $x);
[2 3]
```

But this works partially, without any complaints:
```
pdl> $x = zeroes(1); p append(pdl([2]),pdl([3]), $x);
[3]
```

**Comment by djerius** [comment]
More research:

```
pdl> append( pdl(1), pdl(2), zeroes(3) )
Error in PDL::Primitive::append: parameter 'c' index mn size 2, but ndarray dim has size 3
 at primitive.pd line 1513.
 
pdl> append( pdl([1,1]), pdl(2), zeroes(3) )

pdl> append( pdl([1,1]), pdl(2), zeroes(4) )
Error in PDL::Primitive::append: parameter 'c' index mn size 3, but ndarray dim has size 4
```

Looks like it only complains if the output is too big, not if its too small

**Comment by djerius** [comment]
The message is emitted by [pdl_dim_checks](https://metacpan.org/release/ETJ/PDL-2.084/source/Basic/Core/pdlbroadcast.c#L225), but I'm not familiar enough with the code to know if this is just an issue with append not being strict enough or a larger issue in `pdl_dim_checks`

**Comment by mohawk2** [comment]
It would also have rejected if the output size were too small, but not 1. It was allowing a dim size of 1, which is fine for inputs since that will match any size. The fix here is to allow non-matching size of 1 for inputs, but not to allow that for outputs.

Thanks for the report.
