### ISSUE TITLE
PDL build failing re PDL::Graphics::Gnuplot and executing PDL::Graphics::Simple

### ISSUE THREAD

**Issue by perlboy-emeritus** [PDLPorters/pdl#450]
This is a complicated build issue, or issues, I documented at PerlMonks. I posted there first because I assumed my build problem(s) are pilot error.  However, one Monk suggested there might actually be an issue or issues in the PDL build formula for macOS. He even suggested the PDL developers were currently investigating build failures in macOS.  My issues stem from starting from scratch getting PDL running on a new (refurbished) Intel macBookPro running Monterey 12.6.8. It is too much to re-write here so I would just like to post a link to that discussion on PerlMonks, to wit:

https://perlmonks.org/?node_id=11153860
Your help will be greatly appreciated since I believe I am so close to getting a fully capable PDL up and running on my machine. If you really do have ongoing build issues with macOS, I will be glad to do whatever testing that would be helpful.

**Comment by mohawk2** [comment]
The PDL build was at no point failing anywhere discussed on that PerlMonks post. Nevertheless, thank you for the report.
