### ISSUE TITLE
erroneous results from "range" on higher dimensional piddles

### ISSUE THREAD

**Issue by jo-37** [PDLPorters/pdl#457]
Applying "range" to a 4-d piddle (or higher) gives erroneous results. From the perldoc of "range", a call like
`$p->range(ndcoords($p), 2)` should have all the dimensions of `$p` at the front, followed by a '2' for every dimension of `$p`.
The actual results are completely strange and an error message is emitted.
```
#!/usr/bin/perl

use v5.24;
use warnings;
use PDL;

# correct:
my $p3 = ones 4, 4, 4;
my $idx3 = ndcoords $p3;
say $idx3->info;
say $p3->range($idx3, 2)->info;

# erroneous:
my $p4 = ones 5, 5, 5, 5;
my $idx4 = ndcoords $p4;
say $idx4->info;
say $p4->range($idx4, 2)->info;

# erroneous:
my $p5 = ones 6, 6, 6, 6, 6;
my $idx5 = ndcoords $p5;
say $idx5->info;
say $p5->range($idx5, 2)->info;
```
This prints:
```
PDL: Double D [3,4,4,4]
PDL: Double D [4,4,4,2,2,2]
PDL: Double D [4,5,5,5,5]
PDL: Double D [5,5,5,5,2,2,1,5]
PDL: Double D [5,6,6,6,6,6]
PDL: Double D [6,6,6,6,6,2,1,6,36,216]
	(in cleanup) Error in rangeb:index out-of-bounds in range (index vector #5) at ./pdl-range.pl line 20.
	eval {...} called at ./pdl-range.pl line 20
```
PDL version is v2.084. A prior version (v2.025) aborted with segmentation violation instead.

**Comment by choroba** [comment]
Related discussion: https://www.perlmonks.org/?node_id=11155062

**Comment by mohawk2** [comment]
As noted on PerlMonks:

> The reason why the higher-dim output ndarrays have dims that start with 1, then are powers of the original size, is because the pdl struct has a def_dims array, size 6. Straight after that is the def_dimincs (stride-size at each dimension), also size 6 (the API has code to allocate memory if >6 dims, clearly that's not getting called here). Both are being used, even though there are more than 6 dims. Reading the array of dims will therefore give data that starts out correct, then looks crackers. It's almost certainly a bug in the rangeb code, since higher-dim ndarrays surely get tested elsewhere and the API ought to be solid.

The above information about `def_dims` etc was obtained by adding this to `t/slice.t`:

```
{
my $p3 = ones 2, 2, 2, 2;
my $idx3 = ndcoords indx, $p3;
diag $idx3->info;
diag $idx3;
diag $p3->range($idx3, 3, 't')->info;
}
```

which on running immediately gave a `SIGABRT`. I tracked down where, by running `make core && gdb perl -ex 'run -Mblib t/slice.t'`, and in `gdb` asking for a backtrace (`bt`). On seeing there was a `pdlapi.c` function, I edited `Basic/Core/Makefile` to add `-g` to the `OPTIMIZE =` line, then re-ran the `make core && gdb`:

```
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737350198144)
    at ./nptl/pthread_kill.c:44
[...]
#12 pdl__free (it=it@entry=0x5555558f1e90) at pdlapi.c:269
(gdb) frame 12
#12 pdl__free (it=it@entry=0x5555558f1e90) at pdlapi.c:269
269		    SvREFCNT_dec(it->datasv);
(gdb) list
264		pdl__call_magic(it, PDL_MAGIC_DELETEDATA);
265		pdl__magic_free(it);
266	    }
267	    if(it->datasv) {
268		    PDLDEBUG_f(printf("SvREFCNT_dec datasv=%p\n",it->datasv);)
269		    SvREFCNT_dec(it->datasv);
270		    it->data=0;
271	    } else if(it->data && it->data != &it->value) {
272		    pdl_pdl_warn("Warning: special data without datasv is not freed currently!!");
273	    }
(gdb) p *it
$1 = {magicno = 1111638597, state = 8193, trans_parent = 0x0, vafftrans = 0x0, 
  sv = 0x0, datasv = 0x5555564c9470, data = 0x5555564d8930, badvalue = {
    type = PDL_INVALID, value = {A = 0 '\000', B = 0 '\000', S = 0, U = 0, 
      L = 0, K = 0, N = 0, P = 0, Q = 0, F = 0, D = 0, E = 0, G = 0 + 0i, 
      C = 0 + 0i, H = 0 + 0i}}, has_badvalue = 0, nvals = 288, nbytes = 2304, 
  datatype = PDL_D, dims = 0x5555558f1f90, dimincs = 0x5555558f1fc0, 
  ndims = 8, broadcastids = 0x5555558f1ff0, nbroadcastids = 1, 
  trans_children = {trans = {0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0}, 
    next = 0x0}, def_dims = {2, 2, 2, 2, 3, 3}, def_dimincs = {1, 2, 4, 8, 16, 
    48}, def_broadcastids = {8, 144, 0, 0}, magic = 0x0, hdrsv = 0x0, value = {
    A = 0 '\000', B = 0 '\000', S = 0, U = 0, L = 0, K = 0, N = 0, P = 0, 
    Q = 0, F = 0, D = 0, E = 0, G = 0 + 0i, C = 0 + 0i, H = 0 + 0i}}
(gdb) p it->dims
$2 = (PDL_Indx *) 0x5555558f1f90
(gdb) p &it->def_dims
$3 = (PDL_Indx (*)[6]) 0x5555558f1f90
```

This makes it look like the size-6 `def_dims` is being used, even though `ndims` is 8. I know the C API reallocates `dims` in and out of the `def_dims` when used correct. Inspecting the `rangeb` code, I see: https://github.com/PDLPorters/pdl/blob/68da23cd604ca508e3fc65cb8cd01fcc90bcbffa/Basic/Slices/slices.pd#L847-L849

To see where `$SETNDIMS` is defined, I look at `Basic/Gen/PP.pm`: https://github.com/PDLPorters/pdl/blob/68da23cd604ca508e3fc65cb8cd01fcc90bcbffa/Basic/Gen/PP.pm#L382

Then I check the definition of `pdl_reallocdims` in `Basic/Core/pdlapi.c`: https://github.com/PDLPorters/pdl/blob/68da23cd604ca508e3fc65cb8cd01fcc90bcbffa/Basic/Core/pdlapi.c#L494-L497

This makes it clear that setting the `ndims` *before* calling `reallocdims` is a big mistake. To see how long that's been like this, I looked at `git log -p -w Basic/Slices/slices.pd`, and can see that in 2002, the relevant code was modified but not importantly changed, in dea9e8c3d489a869d0aa53175cb9459123d0d489. This bug has been there all this time.

**Comment by jo-37** [comment]
Great work! Thanks @mohawk2
