### ISSUE TITLE
2.088 build fails on i386 due to test failures

### ISSUE THREAD

**Issue by sebastic** [PDLPorters/pdl#474]
The Debian package build on i386 for PDL 2.088 failed due to test failures:
```
    #   Failed test 'hist works'
    #   at t/primitive-misc.t line 32.
    #          got: '[3 5 1 2 2 1 2 1 0 4]'
    #     expected: '[3 5 1 2 1 2 2 1 0 4]'
    # Looks like you failed 1 test of 1.
#   Failed test 'hist'
#   at t/primitive-misc.t line 33.
# Looks like you failed 1 test of 7.
[...]
Test Summary Report
-------------------
t/pdl_from_string.t      (Wstat: 0 Tests: 144 Failed: 0)
  TODO passed:   60-62
t/primitive-misc.t       (Wstat: 256 (exited 1) Tests: 7 Failed: 1)
  Failed test:  2
  Non-zero exit status: 1
t/primitive-random.t     (Wstat: 0 Tests: 3 Failed: 0)
  TODO passed:   1
Files=45, Tests=2267, 72 wallclock secs ( 0.40 usr  0.12 sys + 65.80 cusr  8.38 csys = 74.70 CPU)
Result: FAIL
Failed 1/45 test programs. 1/2267 subtests failed.
```
Full buildlog: https://salsa.debian.org/perl-team/modules/packages/pdl/-/jobs/5625325

Same failure on the buildds: [i386](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=i386&ver=1%3A2.088-1&stamp=1713781738&raw=0), [hurd-i386](https://buildd.debian.org/status/fetch.php?pkg=pdl&arch=hurd-i386&ver=1%3A2.088-1&stamp=1713788621&raw=0)

The other 32bit architectures like armel & armhf are OK, unlike last time (#469).

**Comment by mohawk2** [comment]
@sebastic The above linked commit makes it work on my 32-bit box. Are you amenable to applying the above commit as a patch on 2.088?

**Comment by sebastic** [comment]
Patch added in [commit 9bb7f548](https://salsa.debian.org/perl-team/modules/packages/pdl/-/commit/9bb7f54832e95435e0ac655c0a7dd2b5ca89b481).

The package build succeeded locally in an i386 chroot, in [Salsa CI](https://salsa.debian.org/perl-team/modules/packages/pdl/-/pipelines/669651), and on the [build daemons](https://buildd.debian.org/status/package.php?p=pdl).

**Comment by mohawk2** [comment]
Thank you for the report, as always!

**Comment by sisyphus** [comment]
Just for fun, one way I could get <code>0.5 / 0.1</code> to evaluate (in C) to less than 5 is if <code>0.1</code> is single precision:
```
#include <stdio.h>
int main(void) {
float f1 = 0.5, f2 = 0.1;
double x;
x = (double)f1 / f2;
printf("%.17g %a\n", x, x);
return 0;
}

/* Outputs: 4.9999999254941949 0x1.3fffffb000001p+2 */
```
(Confirmed using MPFR library.)
Using 64-bit gcc-13.2.0, if that cast to double was removed, then the output changed to <code>5 0x1.4p+2</code>, but using 32-bit gcc-13.2.0, it mattered not whether that cast was specified.
