### ISSUE TITLE
Support for HDF5

### ISSUE THREAD

**Issue by Tux** [PDLPorters/pdl#477]
PDL tries to use Alien::HDF4 to find support for PDL::IO::HDF

My box with openSUSE Tumbleweed only has hdf5:
```
hdf5-1.12.3-1.1.x86_64
hdf5-devel-1.12.3-1.1.x86_64
hdf5-devel-data-1.12.3-1.1.x86_64
libhdf5-200-1.12.3-1.1.x86_64
libhdf5_cpp200-1.12.3-1.1.x86_64
libhdf5_fortran200-1.12.3-1.1.x86_64
libhdf5_hl200-1.12.3-1.1.x86_64
libhdf5_hl_cpp200-1.12.3-1.1.x86_64
libhdf5hl_fortran200-1.12.3-1.1.x86_64
```
Of course Alien::HDF4 will not find that, so PDL won't be able to support hdf5

**Comment by mohawk2** [comment]
Use https://metacpan.org/pod/PDL::IO::HDF5 for HDF5.
