### ISSUE TITLE
ArXiV endorser needed

### ISSUE THREAD

**Issue by drzowie** [PDLPorters/pdl#483]
William Braswell (william.braswell@autoparallel.com) wrote to me asking me to endorse an ArXiV preprint describing the use of PDL in bioinformatics.  It's a really interesting paper, but I don't have the ability to endorse for the CS area of ArXiV (I mainly publish in the astrophysics area).  Anyone who has published three CS papers on ArXiV can endorse -- is any of us both able and willing to have a look at the preprint and endorse it?  

If so, please respond here or write to me (craig.deforest@swri.org) or William, and we'll get it done.

**Comment by mohawk2** [comment]
Did Mr Braswell actually author this paper? I am exceptionally cautious about direct involvement with him or any of his works, given he is the person who refused to change https://www.perlmonks.org/?node_id=11158547

I have not published any papers on ArXiV yet, sadly.

**Comment by mohawk2** [comment]
@chrisarg I gather the paper was yours, and that you no longer need this since you switched your arXiv account settings. The paper is at https://arxiv.org/abs/2406.10271 and discusses both PDL and other high-performance Perl capabilities.
