### ISSUE TITLE
Change in perl blead causes test failures in PDL

### ISSUE THREAD

**Issue by jkeenan** [PDLPorters/pdl#487]
BBC report:
https://github.com/Perl/perl5/issues/22354

Failure has been bisected to https://github.com/Perl/perl5/commit/42cf75238c3687c1b1fad9263614036f7059c2dc, which was committed to blead on Jun 24 2024.

Sample CPANtesters failure report:
http://www.cpantesters.org/cpan/report/f2acc314-35cb-11ef-989b-e9500d8dafec

Failure is in t/01-pptest.t, line 592.

**Comment by Leont** [comment]
So in https://github.com/Perl/perl5/commit/2f4409bf707ec51ce63fd97c981a2c9e08b97241 I aligned the behavior 

``` diff
diff --git Basic/Gen/PP.pm Basic/Gen/PP.pm
index 98f2d5d6..b32a1569 100644
--- Basic/Gen/PP.pm
+++ Basic/Gen/PP.pm
@@ -1032,7 +1032,7 @@ sub typemap_eval { # lifted from ExtUtils::ParseXS::Eval, ignoring eg $ALIAS
   my ($var, $type, $num, $init, $pname, $arg, $ntype, $argoff, $subtype)
     = @$varhash{qw(var type num init pname arg ntype argoff subtype)};
   my $ALIAS;
-  my $rv = eval qq("$code");
+  my $rv = eval qq(qq\a$code\a);
   die $@ if $@;
   $rv;
 }
```

**Comment by mohawk2** [comment]
So what does this mean for PDL? Are you asking me to change the code? Will it work on older EU:PXS? Whose life is better as a result of this "alignment"? When is the new EU:PXS going to be released on CPAN?

**Comment by jkeenan** [comment]
On 6/30/24 17:04, mohawk2 wrote:
> So what does this mean for PDL? Are you asking me to change the code? 
> Will it work on older EU:PXS? Whose life is better as a result of this 
> "alignment"? When is the new EU:PXS going to be released on CPAN?
> 

At this point I'm just the messenger here; I don't have definitive 
answers to all your questions.  At this point I'd simply advise 
following the discussion in the perl GH issue to which I linked.

**Comment by mohawk2** [comment]
> At this point I'm just the messenger here; I don't have definitive answers to all your questions. At this point I'd simply advise following the discussion in the perl GH issue to which I linked.

Fair enough! I will do so.
