### ISSUE TITLE
wfits doesn't preserve line order for multi-line HISTORY strings

### ISSUE THREAD

**Issue by d-lamb** [PDLPorters/pdl#488]
Adding a multi-line HISTORY header field to a fresh ndarray results in the HISTORY fields being written in the correct order.

Adding a multi-line HISTORY header field to an existing FITS header attached to an ndarray results in the HISTORY fields being written in the incorrect order.

The problem seems to happen between [line 1915](https://github.com/PDLPorters/pdl/blob/b1d5e88e9261f716870e1a8aae6fd02c67e51cac/IO/FITS/FITS.pm#L1915) and 1928 in IO/FITS.pm.

See linked PR for a test which shows the problem.  The code is reproduced here for convenience.

```perl
my $f_out;
my $hstr = join("\n",'A'..'G');

$f_out = 'long_history.fits';
my $x = xvals(10);
$x->hdr->{'HISTORY'} = $hstr;
$x->wfits($f_out);
my $xr = rfits($f_out);
is($xr->hdr->{'HISTORY'}, $hstr, 'multi-line HISTORY correct with fresh header'); #PASS
unlink($f_out) or die "couldn't delete $f_out";

$f_out = 'm51_longhist.fits';
my $m51 = rfits('t/m51.fits.fz');
$m51->hdr->{HISTORY} = $hstr;
$m51->wfits($f_out);
my $m51r = rfits($f_out);
is($m51r->hdr->{'HISTORY'}, $hstr, 'multi-line HISTORY correct with pre-existing header'); #FAIL
unlink($f_out) or die "couldn't delete $f_out";
```

**Comment by mohawk2** [comment]
This was due to the classic editing problem of changing text based on indices, but the change also changes the lengths of the text. The solution there, as here, is to start at the back so each change's index is still correct.

By the way, the test above wasn't quite it, since FITS kindly appends a `\n` even if it wasn't there.
