### ISSUE TITLE
Unable to build on Windows since 50318b6

### ISSUE THREAD

**Issue by shawnlaffan** [PDLPorters/pdl#493]
PDL cannot be built on Windows (Strawberry Perl) since commit 50318b6 

Running ```perl Makefile.PL``` at the top of the distribution results in the error below.  

Probably ```$header``` in L72 needs to be quoted, or have its backslashes escaped or converted to forward slashes:
```perl
my $h = do { open my $fh, "<", $header or die "$header: $!"; local $/ = undef; <$fh> };
```

```
ERROR from evaluation of C:\user\git\pdl_repos\pdl\Libtmp/Makefile.PL: ERROR from evaluation of C:\user\git\pdl_repos\pdl\Libtmp\GSL/Makefile.PL: ERROR from evaluation of C:\user\git\pdl_repos\pdl\Libtmp\GSL\CDF/Makefile.PL: C:perls5.40.0.1_PDLcbin..include/gsl/gsl_cdf.h: No such file or directory at C:\user\git\pdl_repos\pdl\Libtmp\GSL\CDF\gsl_cdf.pd line 72.
```

**Comment by mohawk2** [comment]
Ah, quite right - thank you for the report! A local test on Windows shows that `gsl-config --cflags` returns something like:

```
"-IC:\perls\5.40.0.1_PDL\c\bin\..\include/gsl/gsl_cdf.h"
```

which gets turned by `shellwords` into what you see. I'll fix it shortly.
