### ISSUE TITLE
Mirror other PDL repos

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#57]
@wchristian, like you did in #6, could we also do the same for

- [PDL-LinearAlgebra](https://sourceforge.net/p/pdl/pdl-linearalgebra/ci/master/tree/),

  > git clone git://git.code.sf.net/p/pdl/pdl-linearalgebra

- [PDL-Book](https://sourceforge.net/p/pdl/pdl-book/ci/master/tree/),

  > git clone git://git.code.sf.net/p/pdl/pdl-book

- [PDL-Graphics-PLplot](https://sourceforge.net/p/pdl/pdl-graphics-plplot/ci/master/tree/),

  > git clone git://git.code.sf.net/p/pdl/pdl-graphics-plplot

- [PDL-IO-HDF5](https://sourceforge.net/p/pdl/pdl-io-hdf5/ci/master/tree/), 

  > git clone git://git.code.sf.net/p/pdl/pdl-io-hdf5

- [PDL::FFTW](https://sourceforge.net/p/pdl/pdl-fftw/ci/master/tree/)

  > git clone git://git.code.sf.net/p/pdl/pdl-fftw

**Comment by wchristian** [comment]
Will do in a while.

**Comment by zmughal** [comment]
OK, I created the corresponding GitHub repos:

- <https://github.com/PDLPorters/pdl-linearalgebra>
- <https://github.com/PDLPorters/pdl-book>
- <https://github.com/PDLPorters/pdl-graphics-plplot>
- <https://github.com/PDLPorters/pdl-io-hdf5>
- <https://github.com/PDLPorters/pdl-fftw>

**Comment by wchristian** [comment]
This should work:

```
0-59/5 * * * * cd /root/pdl_repo_mirrors/pdl.git && git update-mirror
1-59/5 * * * * cd /root/pdl_repo_mirrors/pdl-linearalgebra.git && git update-mirror
2-59/5 * * * * cd /root/pdl_repo_mirrors/pdl-book.git && git update-mirror
3-59/5 * * * * cd /root/pdl_repo_mirrors/pdl-graphics-plplot.git && git update-mirror
4-59/5 * * * * cd /root/pdl_repo_mirrors/pdl-io-hdf5.git && git update-mirror
0-59/5 * * * * cd /root/pdl_repo_mirrors/pdl-fftw.git && git update-mirror
```

**Comment by zmughal** [comment]
Thanks a bunch, @wchristian++!
