### ISSUE TITLE
This repo very out of date

### ISSUE THREAD

**Issue by mohawk2** [PDLPorters/pdl#6]
The actual core repo on http://sourceforge.net/p/pdl/code/ci/master/tree/ shows commits from Aug. This repo stops at Apr.

**Comment by wchristian** [comment]
Just for matters of documentation, here is the .git/config file:

	[core]
		repositoryformatversion = 0
		filemode = true
		bare = true
	[remote "origin"]
		fetch = +refs/*:refs/*
		mirror = true
		url = git://git.code.sf.net/p/pdl/code
	[remote "github"]
		url = git@github.com:PDLPorters/pdl.git
		fetch = +refs/heads/*:refs/remotes/github/*
		mirror = true
	[alias]
		update-mirror = !git fetch -q origin && git push -q github

**Comment by mohawk2** [comment]
Just read back and the error was mine. False alarm!

**Comment by mohawk2** [comment]
The mirror script is now recreating branches that are deleted on sf.net. The problem is that it needs `--prune` on the fetch in the alias. @wchristian, could you update it?

**Comment by wchristian** [comment]
Amended:

	[core]
		repositoryformatversion = 0
		filemode = true
		bare = true
	[remote "origin"]
		fetch = +refs/*:refs/*
		mirror = true
		url = git://git.code.sf.net/p/pdl/code
	[remote "github"]
		url = git@github.com:PDLPorters/pdl.git
		fetch = +refs/heads/*:refs/remotes/github/*
		mirror = true
	[alias]
		update-mirror = !git fetch --prune -q origin && git push -q github

**Comment by mohawk2** [comment]
This is working superbly! Closing.

**Comment by zmughal** [comment]
@wchristian, could we also do the same for

- [PDL-LinearAlgebra](https://sourceforge.net/p/pdl/pdl-linearalgebra/ci/master/tree/),

  > git clone git://git.code.sf.net/p/pdl/pdl-linearalgebra

- [PDL-Book](https://sourceforge.net/p/pdl/pdl-book/ci/master/tree/),

  > git clone git://git.code.sf.net/p/pdl/pdl-book

- [PDL-Graphics-PLplot](https://sourceforge.net/p/pdl/pdl-graphics-plplot/ci/master/tree/),

  > git clone git://git.code.sf.net/p/pdl/pdl-graphics-plplot

- [PDL-IO-HDF5](https://sourceforge.net/p/pdl/pdl-io-hdf5/ci/master/tree/), 

  > git clone git://git.code.sf.net/p/pdl/pdl-io-hdf5

- [PDL::FFTW](https://sourceforge.net/p/pdl/pdl-fftw/ci/master/tree/)

  > git clone git://git.code.sf.net/p/pdl/pdl-fftw
