### ISSUE TITLE
Data::Printer support

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#61]
The code in _data_printer from `Data::Printer::Filter::PDL` that can be merged into PDL itself.

The other solution would be to create a bundle for PDL and other useful modules to use with it and document this.

**Comment by mohawk2** [comment]
Merging this sort of thing into PDL is the wrong way to go. That's why we have modules in the first place.

**Comment by zmughal** [comment]
I think it is fine as a separate dist. That way the implicit dependency on `Data::Printer` remains explicit.

It is here, by the way: <https://github.com/EntropyOrg/p5-Data-Printer-Filter-PDL>.
