### ISSUE TITLE
Add information about MAX and MIN values of each PDL::Type

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#77]

**Comment by mohawk2** [comment]
I think a review of PDL::Types would be a good idea, and including the above points. Also a note about the treatment of IVs and NVs (including the recent update so NVs are all at least `double` now, with `ldouble` if the value can't be a `double` (only possible on Perls with longdouble). Also a note about complex types including complex long double.

**Comment by mohawk2** [comment]
Fixed (I believe) in 49fc650922ac1a4a61c99aff22b4eb5d8fa94b53
