### ISSUE TITLE
Travis-CI: Make sure coverage includes XS files

### ISSUE THREAD

**Issue by zmughal** [PDLPorters/pdl#92]
See http://blogs.perl.org/users/nick_wellnhofer/2015/03/howto-xs-coverage-reports-on-coveralls.html.

**Comment by mohawk2** [comment]
tl;dr: with gcc

```
make OPTIMIZE="-O0 --coverage" OTHERLDFLAGS="--coverage"
```

Replace `coverage-report` with:

```
if [ "$COVERAGE" -eq 1 ]; then cover -ignore_re '/CORE/\w+\.h$'; fi
```

**Comment by mohawk2** [comment]
In fact you need to (for single-dir distros, i.e. not PDL) set `OPTIMIZE` and `LDDLFLAGS` to the values shown. For multi-dir ones, you need to override perl's `%Config` to achieve this. Also, `gcov2perl` needs running from the repo top-level to preserve filename structure, but `gcov` needs to be run in each subdir else it gets confused.
